// KisanSaathi - Constants & Localization Resources (Zero Mock Data)

export const LANGUAGES = [
  { code: "en", name: "English", native: "English", initial: "EN" },
  { code: "hi", name: "Hindi", native: "हिन्दी", initial: "HI" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", initial: "PA" },
  { code: "mr", name: "Marathi", native: "मराठी", initial: "MR" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", initial: "GU" },
  { code: "bn", name: "Bengali", native: "বাংলা", initial: "BN" },
  { code: "te", name: "Telugu", native: "తెలుగు", initial: "TE" },
  { code: "ta", name: "Tamil", native: "தமிழ்", initial: "TA" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", initial: "KN" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", initial: "ML" },
  { code: "or", name: "Odia", native: "ଓଡ଼ਿਆ", initial: "OR" },
  { code: "ur", name: "Urdu", native: "اردو", initial: "UR" },
  { code: "as", name: "Assamese", native: "অসমীয়া", initial: "AS" },
  { code: "mai", name: "Maithili", native: "मैथिली", initial: "MAI" },
  { code: "sat", name: "Santali", native: "ᱥᱟᱱᱛᱟᱲᱤ", initial: "SAT" },
  { code: "ks", name: "Kashmiri", native: "कॉशुर", initial: "KS" },
  { code: "sd", name: "Sindhi", native: "سنڌي", initial: "SD" },
  { code: "doi", name: "Dogri", native: "डोगरी", initial: "DOI" },
  { code: "kok", name: "Konkani", native: "कोंकणी", initial: "KOK" },
  { code: "brx", name: "Bodo", native: "बर’", initial: "BRX" },
  { code: "mni", name: "Manipuri", native: "মৈতৈলোন্", initial: "MNI" }
];

export const TRANSLATIONS = {
  doi: {
    "appName": "किसानसाथी",
    "tagline": "केंद्रीयकृत फसल खरीद ते समर्था-आधारित स्लाट बुकिंग प्लेटफार्म",
    "heroTitle1": "केंद्रीयकृत फसल खरीद ते",
    "heroTitle2": "समर्था-आधारित शेड्यूलिंग",
    "heroDesc": "पारदर्शी स्लाट बुकिंग, डिजिटल गुणवत्ता जांच ते सीधे बैंक खाते च PFMS राहीं भुगतान।",
    "feat1Title": "समर्था-आधारित बुकिंग",
    "feat1Desc": "मंडी च भीड़ रोकने लेई दैनिक समर्था अनुसार स्लाट आवंटन।",
    "feat2Title": "जमीन रिकार्ड सत्यापन",
    "feat2Desc": "सरकारी रिकार्ड थमां जमीन ते फसल दे ब्योरे दी स्वचालित पुष्टि।",
    "feat3Title": "डिजिटल क्वालिटी ग्रेडिंग",
    "feat3Desc": "नमी ते शुद्धता दी जांच कन्नै लाइव कतार दी स्थिति।",
    "feat4Title": "डिजिटल जे-फार्म ते डीबीटी",
    "feat4Desc": "तुरंत डिजिटल खरीद रसीद ते बैंक खाते च सीधा भुगतान।",
    "farmer": "किसान",
    "official": "विभागीय अधिकारी",
    "farmerSignIn": "किसान साइन इन",
    "newRegistration": "नमीं रजिस्ट्रेशन",
    "mobileNumber": "मोबाइल नंबर",
    "password": "पासवर्ड",
    "signInBtn": "साइन इन करो",
    "quickAccess": "तुरंत पहुंच",
    "quickRoleShortcuts": "अधिकारिक शार्टकट",
    "quickFarmerDemo": "किसान (रमेश कुमार) दे रूप च लाग इन",
    "officialRole": "अधिकारी दा ओहदा",
    "selectOfficialRole": "अधिकारी दा ओहदा चुनो",
    "adminRole": "राज्य प्रशासक",
    "centreAdminRole": "केंद्र प्रशासक",
    "checkinRole": "चेक-इन अधिकारी",
    "qualityRole": "क्वालिटी चेक अधिकारी",
    "weighingRole": "तौल अधिकारी",
    "assignedCentre": "आबंटित खरीद केंद्र",
    "officerId": "अधिकारी आईडी",
    "welcome": "जी आयां गी",
    "switchRole": "लॉग आउट",
    "overview": "मेरी प्रोफ़ाइल",
    "myProfile": "मेरी प्रोफ़ाइल",
    "bookSlot": "स्लाट बुक करो",
    "landRecords": "जमीन दा रिकार्ड",
    "liveQueue": "लाइव कतार स्थिति",
    "receipts": "खरीद रसीदां",
    "activeBooking": "सक्रिय बुकिंग",
    "cancelBooking": "बुकिंग रद्द करो",
    "trackProgress": "स्थिति दिक्खो",
    "digitalPass": "डिजिटल पास",
    "cropAndSeason": "फसल ते मौसम",
    "expectedQty": "अनुमानित मात्रा",
    "procurementCentre": "खरीद केंद्र",
    "appointmentTime": "तय समें",
    "dailyCapacity": "दैनिक समर्था",
    "verifiedArea": "सत्यापित रकबा",
    "activeMsp": "मौजूदा एमएसपी (MSP)",
    "verified": "सत्यापित",
    "pending": "बकाया",
    "enterAadhaar": "12 अंका दा आधार नंबर भरो",
    "sendOtp": "ओटीपी भेजो",
    "enterOtp": "ओटीपी दर्ज करो",
    "verifyOtp": "ओटीपी दी पुष्टि करो",
    "completeReg": "रजिस्ट्रेशन पूरा करियै लाग इन करो",
    "home": "मुख्य सफा",
    "slotBooking": "स्लाट बुकिंग",
    "liveReport": "लाइव मंडी रिपोर्ट",
    "bookingHistory": "बुकिंग इतिहास",
    "procurements": "उपज खरीद",
    "helpSupport": "मदद ते सहायता",
    "alerts": "सूचनाएं",
    "upcomingProcurement": "आगमी खरीद",
    "services": "सेवाएं",
    "viewDetails": "ब्योरा दिक्खो",
    "noActiveBooking": "कोई सक्रिय बुकिंग नेईं ऐ!",
    "bookSlotNow": "हुने स्लाट बुक करो",
    "welcomeBack": "परतियै स्वागत ऐ",
    "notificationsAndAlerts": "सूचनाएं ते अलर्ट",
    "close": "बंद करो",
    "cancel": "रद्द करो",
    "confirmCancel": "रद्द करने दी पुष्टि करो",
    "logoutConfirmTitle": "लॉग आउट दी पुष्टि करो",
    "logoutConfirmDesc": "केह् तुस सचमुच अपने किसानसाथी खाते थमां लॉग आउट करना चांह्दे ओ?",
    "selectLanguage": "बोली चुनो",
    "personalDetails": "निजी ते पहचान ब्योरा",
    "residentialAddress": "रिहायशी पता",
    "verifiedParcels": "सत्यापित जमीन खसरा",
    "liveQueueHeading": "लाइव मंडी खरीद कतार",
    "bookingHistoryHeading": "तुंदा अप्वाइंटमेंट इतिहास",
    "procurementHeading": "खरीद प्रमाण पत्र ते जे-फार्म",
    "contactSupport": "सहायता केंद्र ते हेल्पडेस्क",
    "allAppointments": "सारियां अप्वाइंटमेंट",
    "queueAndDbt": "कतार ते डीबीटी स्थिति",
    "cadastralParcels": "जमीन खसरा ब्योरा",
    "aadhaarAndBank": "आधार ते बैंक ब्योरा",
    "formJReceipts": "जे-फार्म डिजिटल रसीदां",
    "forgotPassword": "पासवर्ड भुल्ली गे?",
    "resetPassword": "पासवर्ड रीसेट करो",
    "resetPasswordDesc": "अपना पंजीकृत मोबाइल नंबर या अधिकारी आईडी दर्ज करो।",
    "enterOtp": "ओटीपी दर्ज करो",
    "newPassword": "नवां पासवर्ड",
    "confirmNewPassword": "नवें पासवर्ड दी पुष्टि करो",
    "enterNewPassword": "नवां पासवर्ड दर्ज करो",
    "reEnterNewPassword": "नवां पासवर्ड परतियै दर्ज करो",
    "submitAndUpdatePassword": "पासवर्ड सबमिट ते अपडेट करो",
    "updatingPassword": "पासवर्ड अपडेट होआ करदा ऐ...",
    "sendOtp": "ओटीपी भेजो",
    "sendingOtp": "भेजेआ जा करदा ऐ...",
    "resendOtp": "ओटीपी परतियै भेजो",
    "enterTenDigitMobile": "10-अंकें दा मोबाइल नंबर दर्ज करो",
    "enterOfficerIdOrMobile": "अधिकारी आईडी / मोबाइल दर्ज करो",
    "otpSentSuccess": "एसएमएस राहीं सत्यापन ओटीपी भेजी दित्ता गेआ",
    "passwordResetSuccess": "पासवर्ड सफलतापूर्वक अपडेट होई गेआ! हुण तुस साइन इन करी सकदे ओ।",
    "passwordResetFailed": "पासवर्ड रीसेट करने च विफलता। कृपा करियै अपना ओटीपी जांचो ते परतियै कोशिश करो।",
    "registeredMobileNumber": "पंजीकृत मोबाइल नंबर",
    "officerIdOrMobile": "अधिकारी आईडी / मोबाइल",
    "newFarmerCreateAccount": "नमां किसान खाता बनाओ",
    "backToSignIn": "साइन इन पर वापस जाओ",
    "farmerRegistrationTitle": "नमां किसान रजिस्ट्रेशन",
    "hello": "नमस्ते",
    "dbtBankAccount": "PFMS प्रत्यक्ष लाभ अंतरण (DBT) बैंक खाता",
    "updateAddBank": "बैंक खाता अपडेट करो / जोड़ो",
    "updateContact": "संपर्क ब्योरा अपडेट करो",
    "updatePassword": "पासवर्ड बदलो",
    "farmerName": "किसान दा नां",
    "fatherName": "पिता दा नां",
    "age": "उमर",
    "ageGender": "उमर / लिंग",
    "aadhaarCardNumber": "आधार कार्ड नंबर",
    "primaryMobile": "मुख्य मोबाइल नंबर",
    "emailAddress": "ईमेल पता",
    "permanentAddress": "पक्का पता",
    "villageTehsil": "ग्रां ते तहसील",
    "districtState": "जिला ते राज्य",
    "agriZone": "कृषि क्षेत्र (जोन)",
    "registryVerification": "रजिस्ट्री सत्यापन",
    "linked": "लिंक कीता गेआ",
    "verifiedUidai": "UIDAI सत्यापित",
    "aadhaarAgriVerified": "आधार ई-केवाईसी ते एग्रीस्टैक सत्यापित",
    "bankAccount": "बैंक खाता",
    "bankName": "बैंक दा नां",
    "accountNumber": "खाता नंबर",
    "ifscCode": "IFSC कोड",
    "branchName": "शाखा दा नां",
    "accountHolder": "खाताधारक दा नां",
    "primaryDbtBank": "मुख्य DBT भुगतान बैंक",
    "dbtStatus": "DBT स्थिति",
    "activeDbtSeeded": "सक्रिय ते PFMS सीडेड",
    "agriCadastreEyebrow": "एग्रीकैडास्टर ते एग्रीस्टैक",
    "agriCadastreDesc": "केंद्रीयकृत भूलेख ते एग्रीस्टैक थमां सत्यापित खसरा ब्योरा।",
    "syncAgriStack": "एग्रीस्टैक सिंक करो",
    "syncingAgriStack": "एग्रीस्टैक सिंक होआ करदा ऐ...",
    "addLand": "जमीन जोड़ो",
    "khasraNoHeader": "खसरा नं.",
    "villageTehsilHeader": "ग्रां ते तहसील",
    "districtHeader": "जिला",
    "areaHeader": "रकबा",
    "soilTypeHeader": "मिट्टी दी किस्म",
    "sourceHeader": "स्रोत",
    "statusHeader": "स्थिति",
    "bookingEyebrow": "फसल खरीद बुकिंग",
    "bookingOpen": "बुकिंग खुली ऐ",
    "bookingDesc": "फसल, सत्यापित जमीन, अनुमानित उपज मात्रा ते अपनी पसंद दा 20-मिनट दा समां स्लाट चुनो।",
    "tokenActive": "सक्रिय टोकन",
    "cropDetailsStep": "फसल दा ब्योरा",
    "cropDetailsDesc": "अपनी उपज दी फसल चुनो",
    "season": "मौसम (सीजन)",
    "cropName": "फसल दा नां",
    "selectLandStep": "जमीन चुनो",
    "selectLandDesc": "ओह् सारियां सत्यापित जमीन खसरे चुनो जित्थै फसल कट्टी गेई ऐ",
    "expectedQtyStep": "अनुमानित उपज मात्रा",
    "expectedQtyDesc": "सारे चुने खसरे दी कुल अनुमानित उपज (टन च) दर्ज करो।",
    "expectedQtyTonnes": "अनुमानित मात्रा (टन च)",
    "centreDateTimeStep": "केंद्र, मिती ते समां स्लाट",
    "centreDateTimeDesc": "खरीद केंद्र ते अपनी पसंद दा समां स्लाट चुनो।",
    "selectTimeSlot": "समां स्लाट चुनो (09:00 AM – 05:00 PM)",
    "bookSlotBtn": "स्लाट बुक करो",
    "bookingSlotBtn": "स्लाट बुक होआ करदा ऐ...",
    "bookingSummary": "बुकिंग ब्योरा",
    "selectedLands": "चुनेदा खसरा",
    "expectedQtyLabel": "अनुमानित मात्रा",
    "centreLabel": "खरीद केंद्र",
    "dateLabel": "मिती",
    "timeSlotLabel": "समां स्लाट",
    "slotConfirmedNote": "डिजिटल पास दे कन्नै स्लाट अप्वाइंटमेंट तुरंत पक्की होग।",
    "liveTrackerEyebrow": "लाइव मंडी कतार ट्रैकर",
    "liveReportDesc": "मंडी च तुंदी फसल खरीद दी लाइव स्थिति ट्रैकिंग।",
    "currentQueue": "मौजूदा कतार",
    "gatePass": "गेट पास",
    "procurementProcessingStages": "फसल खरीद प्रक्रिया दे चरण",
    "stage1": "1. स्लाट बुकिंग सफल",
    "stage2": "2. गेट पर हाजिरी (चेक-इन)",
    "stage3": "3. गुणवत्ता जांच ते ग्रेडिंग",
    "stage4": "4. कांटे पर तौल",
    "stage5": "5. फसल खरीद संपन्न",
    "stage6": "6. PFMS DBT भुगतान",
    "trackPaymentBtn": "भुगतान स्थिति दिक्खने लेई इत्थै क्लिक करो",
    "historyEyebrow": "अप्वाइंटमेंट ते इतिहास",
    "historyDesc": "अपने सारे आगमी, सक्रिय ते पूरे होई चुके स्लाट अप्वाइंटमेंट दा ब्योरा दिक्खो।",
    "viewDetailsQr": "ब्योरा ते क्यूआर (QR) दिक्खो",
    "procurementsEyebrow": "खरीद ते भुगतान रसीदां",
    "procurementsDesc": "बेची गेई उपज, DBT भुगतान ते अधिकारिक डिजिटल जे-फार्म प्रमाण पत्र।",
    "totalCropSold": "कुल बेची गेई उपज",
    "totalMoneyReceived": "कुल प्राप्त भुगतान",
    "pendingPayouts": "बकाया भुगतान",
    "totalTransactions": "कुल लेनदेन (जे-फार्म)",
    "authenticatedJForms": "सत्यापित फसल खरीद रसीदां (जे-फार्म)",
    "viewDownloadJForm": "जे-फार्म दिक्खो / डाउनलोड करो"
},

  en: {
    appName: "KisanSaathi",
    tagline: "Centralized Crop Procurement & Capacity-Aware Slot Booking Platform",
    heroTitle1: "Centralized Crop Procurement &",
    heroTitle2: "Capacity-Aware Scheduling",
    heroDesc: "Streamlined mandi operations with transparent slot reservations, digital quality inspection, automated weighbridge integration, and direct PFMS payments.",
    feat1Title: "Capacity-Aware Booking",
    feat1Desc: "Prevents mandi overcrowding by matching farmer grain loads with verified daily handling limits.",
    feat2Title: "AgriStack & Land Sync",
    feat2Desc: "Automated verification of land parcels and crop records through centralized state registries.",
    feat3Title: "Digital Quality Grading",
    feat3Desc: "Standardized moisture and purity assessment with auto-updating live waiting queues.",
    feat4Title: "Digital J-Form & PFMS DBT",
    feat4Desc: "Instant digital procurement receipts with automated Direct Benefit Transfer processing.",
    farmer: "Farmer",
    official: "Official / Department",
    farmerSignIn: "Farmer Sign In",
    newRegistration: "New Registration",
    mobileNumber: "Mobile Number",
    password: "Password",
    signInBtn: "Sign In",
    quickAccess: "QUICK ACCESS",
    quickRoleShortcuts: "QUICK ROLE SHORTCUTS",
    quickFarmerDemo: "Quick Sign In as Farmer (Ramesh Kumar)",
    officialRole: "Official Role",
    selectOfficialRole: "Select Official Role",
    adminRole: "State Administrator",
    centreAdminRole: "Centre Admin",
    checkinRole: "Check-in Officer",
    qualityRole: "Quality Check Officer",
    weighingRole: "Weighing Officer",
    assignedCentre: "Assigned Procurement Centre",
    officerId: "Officer ID / Mobile Number",
    welcome: "Welcome",
    switchRole: "Logout",
    overview: "My Profile",
    myProfile: "My Profile",
    bookSlot: "Book a slot",
    landRecords: "Land Records",
    liveQueue: "Live Queue Status",
    receipts: "Procurement Receipts",
    activeBooking: "Upcoming Booking Appointment",
    cancelBooking: "Cancel Booking",
    trackProgress: "Track Progress",
    digitalPass: "Digital Check-in Pass",
    cropAndSeason: "Crop & Season",
    expectedQty: "Expected Quantity",
    procurementCentre: "Procurement Centre",
    appointmentTime: "Appointment Time",
    dailyCapacity: "Daily Capacity",
    verifiedArea: "Verified Land Area",
    activeMsp: "Active MSP Rate",
    verified: "Verified",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    resetPasswordDesc: "Enter your registered mobile number or officer ID.",
    enterOtp: "Enter OTP",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    enterNewPassword: "Enter new password",
    reEnterNewPassword: "Re-enter new password",
    submitAndUpdatePassword: "Submit & Update Password",
    updatingPassword: "Updating Password...",
    sendOtp: "Send OTP",
    sendingOtp: "Sending...",
    resendOtp: "Resend OTP",
    enterTenDigitMobile: "Enter 10-digit mobile number",
    enterOfficerIdOrMobile: "Enter officer ID / mobile",
    otpSentSuccess: "Verification OTP sent via SMS to",
    passwordResetSuccess: "Password updated successfully! You can now sign in.",
    passwordResetFailed: "Failed to reset password. Please check your OTP and try again.",
    registeredMobileNumber: "Registered Mobile Number",
    officerIdOrMobile: "Officer ID / Mobile",
    newFarmerCreateAccount: "New farmer? Create an account",
    backToSignIn: "Back to Sign In",
    farmerRegistrationTitle: "Farmer Registration (Aadhaar e-KYC)",
    enterAadhaar: "Enter 12-Digit Aadhaar Number",
    sendOtp: "Send Verification OTP",
    enterOtp: "Enter Verification OTP",
    verifyAadhaarFetch: "Verify Aadhaar & Fetch Profile",
    home: "Home",
    slotBooking: "Slot Booking",
    liveReport: "Live Report",
    bookingHistory: "Booking History",
    procurements: "Procurements",
    helpSupport: "Help & Support",
    alerts: "Alerts",
    upcomingProcurement: "Upcoming Procurement",
    services: "Services",
    viewDetails: "View Details",
    noActiveBooking: "No active booking scheduled!",
    bookSlotNow: "Book a Slot Now",
    welcomeBack: "Welcome back",
    notificationsAndAlerts: "Notifications & Alerts",
    close: "Close",
    cancel: "Cancel",
    confirmCancel: "Confirm Cancellation",
    logoutConfirmTitle: "Confirm Logout",
    logoutConfirmDesc: "Are you sure you want to log out of your KisanSaathi account?",
    selectLanguage: "Select Language",
    personalDetails: "Personal & Identity Details",
    residentialAddress: "Residential Address",
    verifiedParcels: "Verified Land Parcels",
    liveQueueHeading: "Live Mandi Procurement Queue",
    bookingHistoryHeading: "Your Appointment History",
    procurementHeading: "Procurement Certificates & J-Forms",
    contactSupport: "Contact Helpdesk & Support",
    allAppointments: "All Appointments",
    queueAndDbt: "Queue & PFMS Status",
    formJReceipts: "J-Form Digital Receipts",
    tollFreeAndGuide: "Toll-Free & Mandi Guides",
    hello: "Hello",
    dbtBankAccount: "PFMS Direct Benefit Transfer (DBT) Bank Account",
    updateAddBank: "Update / Add Bank",
    updateContact: "Update Contact",
    updatePassword: "Update Password",
    farmerName: "Farmer Name",
    fatherName: "Father's Name",
    age: "Age",
    ageGender: "Age / Gender",
    aadhaarCardNumber: "Aadhaar Card Number",
    primaryMobile: "Primary Mobile Number",
    emailAddress: "Email Address",
    permanentAddress: "Permanent Address",
    villageTehsil: "Village & Tehsil",
    districtState: "District & State",
    agriZone: "Agri-Zone",
    registryVerification: "Registry Verification",
    linked: "Linked",
    verifiedUidai: "UIDAI Verified",
    aadhaarAgriVerified: "Aadhaar e-KYC & AgriStack Verified",
    bankAccount: "Bank Account",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    ifscCode: "IFSC Code",
    branchName: "Branch Name",
    accountHolder: "Account Holder",
    primaryDbtBank: "Primary DBT Payout Bank",
    dbtStatus: "DBT Status",
    activeDbtSeeded: "Active & PFMS Seeded",
    agriCadastreEyebrow: "AGRICADASTRE & AGRISTACK",
    agriCadastreDesc: "Centralized cadastral verification and verified land titles.",
    syncAgriStack: "Sync AgriStack",
    syncingAgriStack: "Syncing AgriStack...",
    addLand: "Add Land",
    khasraNoHeader: "KHASRA NO.",
    villageTehsilHeader: "VILLAGE & TEHSIL",
    districtHeader: "DISTRICT",
    areaHeader: "AREA",
    soilTypeHeader: "SOIL TYPE",
    sourceHeader: "SOURCE",
    statusHeader: "STATUS",
    bookingEyebrow: "PROCUREMENT BOOKING",
    bookingOpen: "Booking open",
    bookingDesc: "Select crop, verified lands, expected produce quantity and your preferred 20-minute appointment slot.",
    tokenActive: "Token Active",
    cropDetailsStep: "Crop details",
    cropDetailsDesc: "Choose the crop you're bringing",
    season: "Season",
    cropName: "Crop name",
    selectLandStep: "Select land",
    selectLandDesc: "Select all verified land parcels where this crop was harvested",
    expectedQtyStep: "Expected quantity",
    expectedQtyDesc: "Enter total expected grain weight across all selected parcels.",
    expectedQtyTonnes: "Expected quantity (Tonnes)",
    centreDateTimeStep: "Centre, date & time slot",
    centreDateTimeDesc: "Choose procurement centre and your preferred time slot.",
    selectTimeSlot: "Select Time Slot (09:00 AM – 05:00 PM)",
    bookSlotBtn: "Book Slot",
    bookingSlotBtn: "Booking slot...",
    bookingSummary: "Booking summary",
    selectedLands: "Selected Lands",
    expectedQtyLabel: "Expected Qty",
    centreLabel: "Centre",
    dateLabel: "Date",
    timeSlotLabel: "Time Slot",
    slotConfirmedNote: "Slot appointment is confirmed with instant digital gate pass.",
    liveTrackerEyebrow: "LIVE MANDI TRACKER",
    liveReportDesc: "Real-time tracking of your current procurement processing at mandi.",
    currentQueue: "Current Queue",
    gatePass: "Gate Pass",
    procurementProcessingStages: "Procurement Processing Stages",
    stage1: "1. Booking Confirmed",
    stage2: "2. Gate Check-in",
    stage3: "3. Quality Check",
    stage4: "4. Weighbridge",
    stage5: "5. Procurement Completed",
    stage6: "6. PFMS DBT Payment",
    trackPaymentBtn: "Click Here to Track Payment Status",
    historyEyebrow: "APPOINTMENTS & JOURNEY",
    historyDesc: "View all your upcoming, active, and completed grain delivery appointments.",
    viewDetailsQr: "View Details & QR",
    procurementsEyebrow: "TRANSACTIONS & PAYMENTS",
    procurementsDesc: "Summary of crop sold, PFMS DBT payouts, and authenticated digital J-Form certificates.",
    totalCropSold: "Total Crop Sold",
    totalMoneyReceived: "Total Money Received",
    pendingPayouts: "Pending Payouts",
    totalTransactions: "Total Transactions",
    authenticatedJForms: "Authenticated Procurement Receipts (J-Forms)",
    viewDownloadJForm: "View / Download J-Form"
  },
  bn: {
    appName: "কিষাণসেতু",
    tagline: "কেন্দ্রীভূত শস্য সংগ্রহ ও ক্ষমতা-সচেতন স্লট বুকিং প্ল্যাটফর্ম",
    heroTitle1: "কেন্দ্রীভূত শস্য সংগ্রহ ও",
    heroTitle2: "ক্ষমতা-সচেতন স্লট বুকিং",
    heroDesc: "স্বচ্ছ স্লট বুকিং, ডিজিটাল গুণমান পরীক্ষা, স্বয়ংক্রিয় ওয়েব্রিজ সংযোগ এবং সরাসরি PFMS ডিবিটি পেমেন্টের মাধ্যমে মাণ্ডি কার্যকারিতা বৃদ্ধি।",
    feat1Title: "ক্ষমতা-সচেতন বুকিং",
    feat1Desc: "দৈনিক প্রক্রিয়াকরণ ক্ষমতার সাথে মিল রেখে মাণ্ডির অতিরিক্ত ভিড় প্রতিরোধ করে।",
    feat2Title: "এগ্রিস্ট্যাক ও জমি যাচাই",
    feat2Desc: "সরকারি রেকর্ড থেকে জমির খতিয়ান এবং ফসলের তথ্যের স্বয়ংক্রিয় যাচাইকরণ।",
    feat3Title: "ডিজিটাল গুণমান গ্রেডিং",
    feat3Desc: "আর্দ্রতা ও বিশুদ্ধতার ডিজিটাল পরীক্ষা এবং লাইভ প্রতীক্ষা তালিকা।",
    feat4Title: "ডিজিটাল জে-ফর্ম ও ডিবিটি",
    feat4Desc: "তাত্ক্ষণিক ডিজিটাল রশিদ এবং সরাসরি ব্যাংক অ্যাকাউন্টে মূল্য প্রদান।",
    farmer: "কৃষক",
    official: "বিভাগীয় কর্মকর্তা",
    farmerSignIn: "কৃষক লগ ইন",
    newRegistration: "নতুন নিবন্ধন",
    mobileNumber: "মোবাইল নম্বর",
    password: "পাসওয়ার্ড",
    signInBtn: "লগ ইন করুন",
    quickAccess: "দ্রুত প্রবেশ",
    quickRoleShortcuts: "ভূমিকা শর্টকাট",
    quickFarmerDemo: "কৃষক (রমেশ কুমার) হিসেবে দ্রুত লগ ইন",
    officialRole: "কর্মকর্তার পদ",
    selectOfficialRole: "কর্মকর্তার পদ নির্বাচন করুন",
    adminRole: "রাজ্য প্রশাসক",
    centreAdminRole: "কেন্দ্র প্রশাসক",
    checkinRole: "চেক-ইন কর্মকর্তা",
    qualityRole: "গুণমান পরীক্ষা কর্মকর্তা",
    weighingRole: "ওজন কর্মকর্তা",
    assignedCentre: "বরাদ্দকৃত ক্রয় কেন্দ্র",
    officerId: "কর্মকর্তা আইডি",
    welcome: "স্বাগতম",
    switchRole: "লগ আউট / পদ পরিবর্তন",
    overview: "ড্যাশবোর্ড সারসংক্ষেপ",
    myProfile: "আমার প্রোফাইল",
    bookSlot: "স্লট বুক করুন",
    landRecords: "জমির রেকর্ড",
    liveQueue: "লাইভ কাতার অবস্থা",
    receipts: "ক্রয় রশিদ (জে-ফর্ম)",
    activeBooking: "সক্রিয় বুকিং অ্যাপয়েন্টমেন্ট",
    cancelBooking: "বুকিং বাতিল করুন",
    trackProgress: "অগ্রগতি দেখুন",
    digitalPass: "ডিজিটাল চেক-ইন পাস",
    cropAndSeason: "ফসল ও মরশুম",
    expectedQty: "প্রত্যাশিত পরিমাণ",
    procurementCentre: "ক্রয় কেন্দ্র",
    appointmentTime: "অ্যাপয়েন্টমেন্ট সময়",
    dailyCapacity: "দৈনিক ক্ষমতা",
    verifiedArea: "যাচাইকৃত জমির পরিমাণ",
    activeMsp: "বর্তমান এমএসপি রেট",
    verified: "যাচাইকৃত",
    pending: "অপেক্ষমাণ",
    enterAadhaar: "১২ সংখ্যার আধার নম্বর লিখুন",
    sendOtp: "যাচাইকরণ ওটিপি পাঠান",
    enterOtp: "৪ সংখ্যার ওটিপি লিখুন",
    verifyOtp: "ওটিপি যাচাই করুন",
    completeReg: "নিবন্ধন সম্পন্ন করে লগ ইন করুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    newFarmerCreateAccount: "নতুন কৃষক? অ্যাকাউন্ট তৈরি করুন",
    backToSignIn: "সাইন ইন-এ ফিরে যান",
    farmerRegistrationTitle: "কৃষক নিবন্ধন (আধার ই-কেওয়াইসি)",
    home: "হোম",
    slotBooking: "স্লট বুকিং",
    liveReport: "লাইভ মাণ্ডি রিপোর্ট",
    bookingHistory: "বুকিং ইতিহাস",
    procurements: "শস্য সংগ্রহ",
    helpSupport: "সাহায্য ও সহায়তা",
    alerts: "সতর্কতা",
    upcomingProcurement: "আসন্ন সংগ্রহ",
    services: "পরিষেবা",
    viewDetails: "বিবরণ দেখুন",
    noActiveBooking: "কোনো সক্রিয় বুকিং নির্ধারিত নেই!",
    bookSlotNow: "এখনই স্লট বুক করুন",
    welcomeBack: "পুনরায় স্বাগতম",
    notificationsAndAlerts: "বিজ্ঞপ্তি ও সতর্কতা",
    close: "বন্ধ করুন",
    cancel: "বাতিল করুন",
    confirmCancel: "বাতিলকরণ নিশ্চিত করুন",
    logoutConfirmTitle: "লগ আউট নিশ্চিত করুন",
    logoutConfirmDesc: "আপনি কি কিষাণসেতু অ্যাকাউন্ট থেকে লগ আউট করতে চান?",
    selectLanguage: "ভাষা নির্বাচন করুন",
    personalDetails: "ব্যক্তিগত ও পরিচয় বিবরণ",
    residentialAddress: "আবাসিক ঠিকানা",
    verifiedParcels: "যাচাইকৃত জমি",
    liveQueueHeading: "লাইভ মাণ্ডি ক্রয় কাতার",
    bookingHistoryHeading: "আপনার অ্যাপয়েন্টমেন্টের ইতিহাস",
    procurementHeading: "ক্রয় সার্টিফিকেট ও জে-ফর্ম",
    contactSupport: "সহায়তা ও হেল্পডেস্ক",
    allAppointments: "সমস্ত অ্যাপয়েন্টমেন্ট",
    queueAndDbt: "কাতার ও পিএফএমএস স্থিতি",
    cadastralParcels: "জমির খতিয়ান বিবরণ",
    aadhaarAndBank: "আধার ও ব্যাংক তথ্য",
    formJReceipts: "জে-ফর্ম ডিজিটাল রশিদ",
    tollFreeAndGuide: "টোল-ফ্রি ও নির্দেশিকা"
  },
  hi: {
    appName: "किसानसाथी",
    tagline: "केंद्रीकृत फसल खरीद एवं क्षमता-आधारित स्लॉट बुकिंग मंच",
    heroTitle1: "केंद्रीकृत फसल खरीद एवं",
    heroTitle2: "क्षमता-आधारित शेड्यूलिंग",
    heroDesc: "पारदर्शी स्लॉट आरक्षण, डिजिटल गुणवत्ता जांच, स्वचालित वेईब्रिज एवं प्रत्यक्ष पीएफएमएस भुगतान के साथ सुव्यवस्थित मंडी संचालन।",
    feat1Title: "क्षमता-आधारित स्लॉट बुकिंग",
    feat1Desc: "दैनिक प्रसंस्करण क्षमता के अनुसार स्लॉट आवंटन करके मंडियों में भीड़ की रोकथाम।",
    feat2Title: "एग्रीस्टैक एवं भूमि रिकॉर्ड सिंक",
    feat2Desc: "सरकारी भूलेख एवं एग्रीस्टैक से खसरा एवं भूमि विवरण का स्वतः सत्यापन।",
    feat3Title: "डिजिटल गुणवत्ता ग्रेडिंग",
    feat3Desc: "नमी एवं शुद्धता की मानकीकृत जांच और स्वतः अपडेट होने वाली लाइव कतार।",
    feat4Title: "डिजिटल जे-फॉर्म एवं डीबीटी भुगतान",
    feat4Desc: "डिजिटल खरीद रसीद और पीएफएमएस द्वारा बैंक खाते में सीधा भुगतान।",
    farmer: "किसान",
    official: "विभागीय अधिकारी",
    farmerSignIn: "किसान लॉग इन",
    newRegistration: "नया पंजीकरण",
    mobileNumber: "मोबाइल नंबर",
    password: "पासवर्ड",
    signInBtn: "लॉग इन करें",
    quickAccess: "त्वरित प्रवेश",
    quickRoleShortcuts: "त्वरित भूमिका शॉर्टकट",
    quickFarmerDemo: "किसान (रमेश कुमार) के रूप में तुरंत लॉग इन करें",
    officialRole: "अधिकारी का पद",
    selectOfficialRole: "अधिकारी का पद चुनें",
    adminRole: "राज्य प्रशासक",
    centreAdminRole: "केंद्र प्रशासक",
    checkinRole: "चेक-इन अधिकारी",
    qualityRole: "गुणवत्ता परीक्षक",
    weighingRole: "तौल अधिकारी",
    assignedCentre: "आवंटित खरीद केंद्र",
    officerId: "अधिकारी आईडी / मोबाइल नंबर",
    welcome: "स्वागत है",
    switchRole: "लॉग आउट",
    overview: "मेरी प्रोफ़ाइल",
    myProfile: "मेरी प्रोफ़ाइल",
    bookSlot: "स्लॉट बुक करें",
    landRecords: "भूमि रिकॉर्ड",
    liveQueue: "लाइव कतार स्थिति",
    receipts: "खरीद रसीदें",
    activeBooking: "सक्रिय खरीद नियुक्ति",
    cancelBooking: "बुकिंग रद्द करें",
    trackProgress: "प्रगति ट्रैक करें",
    digitalPass: "डिजिटल चेक-इन पास",
    cropAndSeason: "फसल एवं मौसम",
    expectedQty: "अनुमानित मात्रा",
    procurementCentre: "खरीद केंद्र",
    appointmentTime: "नियुक्ति समय",
    dailyCapacity: "दैनिक क्षमता",
    verifiedArea: "सत्यापित भूमि क्षेत्र",
    activeMsp: "सक्रिय एमएसपी दर",
    verified: "सत्यापित",
    pending: "प्रतीक्षारत",
    enterAadhaar: "12 अंकों का आधार नंबर दर्ज करें",
    enterOtp: "ओटीपी दर्ज करें",
    verifyOtp: "ओटीपी सत्यापित करें",
    completeReg: "पंजीकरण पूर्ण कर लॉग इन करें",
    forgotPassword: "पासवर्ड भूल गए?",
    resetPassword: "पासवर्ड रीसेट करें",
    resetPasswordDesc: "अपना पंजीकृत मोबाइल नंबर या अधिकारी आईडी दर्ज करें।",
    newPassword: "नया पासवर्ड",
    confirmNewPassword: "नए पासवर्ड की पुष्टि करें",
    enterNewPassword: "नया पासवर्ड दर्ज करें",
    reEnterNewPassword: "नया पासवर्ड पुनः दर्ज करें",
    submitAndUpdatePassword: "पासवर्ड सबमिट व अपडेट करें",
    updatingPassword: "पासवर्ड अपडेट हो रहा है...",
    sendOtp: "ओटीपी भेजें",
    sendingOtp: "भेजा जा रहा है...",
    resendOtp: "ओटीपी पुनः भेजें",
    enterTenDigitMobile: "10 अंकों का मोबाइल नंबर दर्ज करें",
    enterOfficerIdOrMobile: "अधिकारी आईडी / मोबाइल दर्ज करें",
    otpSentSuccess: "एसएमएस के माध्यम से सत्यापन ओटीपी भेजा गया",
    passwordResetSuccess: "पासवर्ड सफलतापूर्वक अपडेट हो गया! अब आप साइन इन कर सकते हैं।",
    passwordResetFailed: "पासवर्ड रीसेट करने में विफलता। कृपया अपना ओटीपी जांचें और पुनः प्रयास करें।",
    registeredMobileNumber: "पंजीकृत मोबाइल नंबर",
    officerIdOrMobile: "अधिकारी आईडी / मोबाइल",
    newFarmerCreateAccount: "नए किसान? खाता बनाएं",
    backToSignIn: "साइन इन पर वापस जाएं",
    farmerRegistrationTitle: "किसान पंजीकरण (आधार ई-केवाईसी)",
    home: "होम",
    slotBooking: "स्लॉट बुकिंग",
    liveReport: "लाइव रिपोर्ट",
    bookingHistory: "बुकिंग इतिहास",
    procurements: "उपज खरीद",
    helpSupport: "सहायता एवं समर्थन",
    alerts: "अलर्ट",
    upcomingProcurement: "आगामी खरीद",
    services: "सेवाएं",
    viewDetails: "विवरण देखें",
    noActiveBooking: "कोई सक्रिय बुकिंग निर्धारित नहीं है!",
    bookSlotNow: "अभी स्लॉट बुक करें",
    welcomeBack: "पुनः स्वागत है",
    notificationsAndAlerts: "सूचनाएं एवं अलर्ट",
    close: "बंद करें",
    cancel: "रद्द करें",
    confirmCancel: "रद्दीकरण की पुष्टि करें",
    logoutConfirmTitle: "लॉग आउट की पुष्टि करें",
    logoutConfirmDesc: "क्या आप वाकई अपने किसानसाथी खाते से लॉग आउट करना चाहते हैं?",
    selectLanguage: "भाषा चुनें",
    personalDetails: "व्यक्तिगत एवं पहचान विवरण",
    residentialAddress: "निवास का पता",
    verifiedParcels: "सत्यापित भूमि खसरा",
    liveQueueHeading: "लाइव मंडी खरीद कतार",
    bookingHistoryHeading: "आपका अपॉइंटमेंट इतिहास",
    procurementHeading: "खरीद प्रमाण पत्र एवं जे-फॉर्म",
    contactSupport: "हेल्पडेस्क एवं सहायता",
    allAppointments: "सभी अपॉइंटमेंट",
    queueAndDbt: "कतार एवं डीबीटी स्थिति",
    formJReceipts: "जे-फॉर्म डिजिटल रसीदें",
    tollFreeAndGuide: "टोल-फ्री एवं मंडी मार्गदर्शिका",
    hello: "नमस्ते",
    dbtBankAccount: "पीएफएमएस प्रत्यक्ष लाभ अंतरण (डीबीटी) बैंक खाता",
    updateAddBank: "बैंक खाता अपडेट करें / जोड़ें",
    updateContact: "संपर्क विवरण अपडेट करें",
    updatePassword: "पासवर्ड बदलें",
    farmerName: "किसान का नाम",
    fatherName: "पिता का नाम",
    age: "आयु",
    ageGender: "आयु / लिंग",
    aadhaarCardNumber: "आधार कार्ड नंबर",
    primaryMobile: "मुख्य मोबाइल नंबर",
    emailAddress: "ईमेल पता",
    permanentAddress: "स्थायी पता",
    villageTehsil: "ग्राम एवं तहसील",
    districtState: "जिला एवं राज्य",
    agriZone: "कृषि क्षेत्र (जोन)",
    registryVerification: "रजिस्ट्री सत्यापन",
    linked: "लिंक किया गया",
    verifiedUidai: "यूआईडीएआई सत्यापित",
    aadhaarAgriVerified: "आधार ई-केवाईसी एवं एग्रीस्टैक सत्यापित",
    bankAccount: "बैंक खाता",
    bankName: "बैंक का नाम",
    accountNumber: "खाता संख्या",
    ifscCode: "आईएफएससी कोड",
    branchName: "शाखा का नाम",
    accountHolder: "खाताधारक का नाम",
    primaryDbtBank: "मुख्य डीबीटी भुगतान बैंक",
    dbtStatus: "डीबीटी स्थिति",
    activeDbtSeeded: "सक्रिय एवं पीएफएमएस सीडेड",
    agriCadastreEyebrow: "एग्रीकैडस्ट्र व एग्रीस्टैक",
    agriCadastreDesc: "केन्द्रीयकृत भूलेख एवं एग्रीस्टैक से सत्यापित खसरा विवरण।",
    syncAgriStack: "एग्रीस्टैक सिंक करें",
    syncingAgriStack: "एग्रीस्टैक सिंक हो रहा है...",
    addLand: "भूमि जोड़ें",
    khasraNoHeader: "खसरा सं.",
    villageTehsilHeader: "गांव एवं तहसील",
    districtHeader: "जिला",
    areaHeader: "क्षेत्रफल",
    soilTypeHeader: "मिट्टी का प्रकार",
    sourceHeader: "स्रोत",
    statusHeader: "स्थिति",
    bookingEyebrow: "फसल खरीद बुकिंग",
    bookingOpen: "बुकिंग चालू",
    bookingDesc: "फसल, सत्यापित भूमि, अनुमानित उपज मात्रा और अपनी पसंद का 20-मिनट का समय स्लॉट चुनें।",
    tokenActive: "सक्रिय टोकन",
    cropDetailsStep: "फसल का विवरण",
    cropDetailsDesc: "अपनी उपज की फसल चुनें",
    season: "मौसम (सीजन)",
    cropName: "फसल का नाम",
    selectLandStep: "भूमि चुनें",
    selectLandDesc: "वे सभी सत्यापित भूमि खसरे चुनें जहां फसल काटी गई है",
    expectedQtyStep: "अनुमानित उपज मात्रा",
    expectedQtyDesc: "सभी चयनित खसरों की कुल अनुमानित उपज (टन में) दर्ज करें।",
    expectedQtyTonnes: "अनुमानित मात्रा (टन में)",
    centreDateTimeStep: "केंद्र, दिनांक एवं समय स्लॉट",
    centreDateTimeDesc: "खरीद केंद्र और अपनी पसंद का समय स्लॉट चुनें।",
    selectTimeSlot: "समय स्लॉट चुनें (09:00 AM – 05:00 PM)",
    bookSlotBtn: "स्लॉट बुक करें",
    bookingSlotBtn: "स्लॉट बुक हो रहा है...",
    bookingSummary: "बुकिंग विवरण",
    selectedLands: "चयनित खसरा",
    expectedQtyLabel: "अनुमानित मात्रा",
    centreLabel: "खरीद केंद्र",
    dateLabel: "दिनांक",
    timeSlotLabel: "समय स्लॉट",
    slotConfirmedNote: "डिजिटल पास के साथ स्लॉट अपॉइंटमेंट तुरंत कन्फर्म होगा।",
    liveTrackerEyebrow: "लाइव मंडी कतार ट्रैकर",
    liveReportDesc: "मंडी में आपकी फसल खरीद का लाइव स्थिति ट्रैकिंग।",
    currentQueue: "वर्तमान कतार",
    gatePass: "गेट पास",
    procurementProcessingStages: "फसल खरीद प्रक्रिया चरण",
    stage1: "1. स्लॉट बुकिंग सफल",
    stage2: "2. गेट पर उपस्थिति (चेक-इन)",
    stage3: "3. गुणवत्ता जांच एवं ग्रेडिंग",
    stage4: "4. वेईब्रिज पर तौल",
    stage5: "5. फसल खरीद संपन्न",
    stage6: "6. पीएफएमएस डीबीटी भुगतान",
    trackPaymentBtn: "भुगतान स्थिति देखने के लिए यहां क्लिक करें",
    historyEyebrow: "अप्वाइंटमेंट एवं इतिहास",
    historyDesc: "अपने सभी आगामी, सक्रिय एवं पूर्ण हो चुके स्लॉट अपॉइंटमेंट का विवरण देखें।",
    viewDetailsQr: "विवरण एवं क्यूआर देखें",
    procurementsEyebrow: "खरीद एवं भुगतान रसीदें",
    procurementsDesc: "बेची गई उपज, डीबीटी भुगतान और आधिकारिक डिजिटल जे-फॉर्म प्रमाण पत्र।",
    totalCropSold: "कुल बेची गई उपज",
    totalMoneyReceived: "कुल प्राप्त भुगतान",
    pendingPayouts: "बकाया भुगतान",
    totalTransactions: "कुल लेनदेन (जे-फॉर्म)",
    authenticatedJForms: "सत्यापित फसल खरीद रसीदें (जे-फॉर्म)",
    viewDownloadJForm: "जे-फॉर्म देखें / डाउनलोड करें"
  },
  te: {
    appName: "కిసాన్‌సేతు",
    tagline: "కేంద్రీకృత పంట సేకరణ మరియు సామర్థ్య ఆధారిత స్లాట్ బుకింగ్ ప్లాట్‌ఫారమ్",
    heroTitle1: "కేంద్రీకృత పంట సేకరణ మరియు",
    heroTitle2: "సామర్థ్య ఆధారిత స్లాట్ బుకింగ్",
    heroDesc: "పారదర్శక స్లాట్ రిజర్వేషన్లు, డిజిటల్ నాణ్యత తనిఖీ మరియు నేరుగా PFMS ఖాతా చెల్లింపులు.",
    feat1Title: "సామర్థ్య ఆధారిత బుకింగ్",
    feat1Desc: "మార్కెట్ యార్డులలో రద్దీని నివారించడానికి రోజువారీ సామర్థ్యానికి అనుగుణంగా స్లాట్లు.",
    feat2Title: "అగ్రిస్టాక్ & భూ రికార్డులు",
    feat2Desc: "భూ రికార్డులు మరియు పంట వివరాల ఆటోమేటిక్ ధృవీకరణ.",
    feat3Title: "డిజిటల్ నాణ్యత గ్రేడింగ్",
    feat3Desc: "తేమ శాతం మరియు నాణ్యత పరీక్షలతో ప్రత్యక్ష క్యూ సమాచారం.",
    feat4Title: "డిజిటల్ రసీదు & డీబీటీ",
    feat4Desc: "తక్షణ డిజిటల్ రశీదు మరియు బ్యాంకు ఖాతాకు నేరుగా నిధుల బదిలీ.",
    farmer: "రైతు",
    official: "అధికారి / విభాగం",
    farmerSignIn: "రైతు లాగిన్",
    newRegistration: "కొత్త నమోదు",
    mobileNumber: "మొబైల్ నంబర్",
    password: "పాస్‌వర్డ్",
    signInBtn: "లాగిన్ అవ్వండి",
    quickAccess: "త్వరిత యాక్సెస్",
    quickRoleShortcuts: "అధికారిక పాత్రలు",
    quickFarmerDemo: "రైతు (రమేష్ కుమార్)గా లాగిన్",
    officialRole: "అధికారి హోదా",
    selectOfficialRole: "అధికారి హోదాను ఎంచుకోండి",
    adminRole: "రాష్ట్ర అడ్మినిస్ట్రేటర్",
    centreAdminRole: "కేంద్ర అడ్మిన్",
    checkinRole: "చెక్-ఇన్ అధికారి",
    qualityRole: "నాణ్యత తనిఖీ అధికారి",
    weighingRole: "తూకం అధికారి",
    assignedCentre: "కేటాయించిన సేకరణ కేంద్రం",
    officerId: "అధికారి ఐడీ",
    welcome: "స్వాగతం",
    switchRole: "లాగ్ అవుట్ / పాత్ర మార్చండి",
    overview: "డ్యాష్‌బోర్డ్ సారాంశం",
    bookSlot: "స్లాట్ బుక్ చేయండి",
    landRecords: "భూమి రికార్డులు",
    liveQueue: "లైవ్ క్యూ స్థితి",
    receipts: "కొనుగోలు రసీదులు",
    activeBooking: "యాక్టివ్ బుకింగ్",
    cancelBooking: "బుకింగ్ రద్దు చేయండి",
    trackProgress: "స్థితిని ట్రాక్ చేయండి",
    digitalPass: "డిజిటల్ చెక్-ఇన్ పాస్",
    cropAndSeason: "పంట & సీజన్",
    expectedQty: "అంచనా పరిమాణం",
    procurementCentre: "సేకరణ కేంద్రం",
    appointmentTime: "నియామక సమయం",
    dailyCapacity: "రోజువారీ సామర్థ్యం",
    verifiedArea: "ధృవీకరించబడిన భూమి",
    activeMsp: "ప్రస్తుత ఎంఎస్‌పి",
    verified: "ధృవీకరించబడింది",
    pending: "పెండింగ్‌లో ఉంది",
    enterAadhaar: "12 అంకెల ఆధార్ నంబర్ నమోదు చేయండి",
    sendOtp: "ఓటీపీ పంపండి",
    enterOtp: "4 అంకెల ఓటీపీని నమోదు చేయండి",
    verifyOtp: "ఓటీపీని ధృవీకరించండి",
    completeReg: "నమోదు పూర్తి చేసి లాగిన్ అవ్వండి",
    home: "హోమ్",
    slotBooking: "స్లాట్ బుకింగ్",
    liveReport: "లైవ్ నివేదిక",
    bookingHistory: "బుకింగ్ చరిత్ర",
    procurements: "ధాన్య సేకరణ",
    helpSupport: "సహాయం & మద్దతు",
    alerts: "హెచ్చరికలు",
    upcomingProcurement: "రాబోయే సేకరణ",
    services: "సేవలు",
    viewDetails: "వివరాలు చూడండి",
    noActiveBooking: "సక్రియ బుకింగ్ ఏదీ లేదు!",
    bookSlotNow: "ఇప్పుడే స్లాట్ బుక్ చేయండి",
    welcomeBack: "తిరిగి స్వాగతం",
    notificationsAndAlerts: "నోటిఫికేషన్లు & హెచ్చరికలు",
    close: "మూసివేయి",
    cancel: "రద్దు చేయి",
    confirmCancel: "రద్దును ధృవీకరించండి",
    logoutConfirmTitle: "లాగ్ అవుట్ నిర్ధారించండి",
    logoutConfirmDesc: "మీరు కిసాన్‌సేతు ఖాతా నుండి లాగ్ అవుట్ కావాలనుకుంటున్నారా?",
    selectLanguage: "భాషను ఎంచుకోండి",
    personalDetails: "వ్యక్తిగత & గుర్తింపు వివరాలు",
    residentialAddress: "నివాస చిరునామా",
    verifiedParcels: "ధృవీకరించబడిన భూమి",
    liveQueueHeading: "లైవ్ మండి సేకరణ క్యూ",
    bookingHistoryHeading: "మీ అపాయింట్‌మెంట్ చరిత్ర",
    procurementHeading: "సేకరణ ధృవీకరణ పత్రాలు & J-ఫారమ్‌లు",
    contactSupport: "సహాయ కేంద్రం & మద్దతు",
    allAppointments: "అన్ని అపాయింట్‌మెంట్లు",
    queueAndDbt: "క్యూ & DBT స్థితి",
    cadastralParcels: "భూమి రికార్డు వివరాలు",
    aadhaarAndBank: "ఆధార్ & బ్యాంక్ వివరాలు",
    formJReceipts: "J-ఫారమ్ డిజిటల్ రసీదులు",
    tollFreeAndGuide: "టోల్-ఫ్రీ & మార్గదర్శకాలు"
  },
  mr: {
    appName: "किसानसेतू",
    tagline: "केंद्रीकृत पीक खरेदी आणि क्षमता-आधारित स्लॉट बुकिंग प्लॅटफॉर्म",
    heroTitle1: "केंद्रीकृत पीक खरेदी आणि",
    heroTitle2: "क्षमता-आधारित स्लॉट बुकिंग",
    heroDesc: "पारदर्शक स्लॉट आरक्षण, डिजिटल गुणवत्ता तपासणी, स्वयंचलित वेईब्रिज आणि थेट बँक खात्यात PFMS पेमेंट.",
    feat1Title: "क्षमता-आधारित बुकिंग",
    feat1Desc: "मार्केट यार्डमधील गर्दी टाळण्यासाठी दैनंदिन क्षमतेनुसार स्लॉट वाटप.",
    feat2Title: "अ‍ॅग्रीस्टॅक व भूमी अभिलेख",
    feat2Desc: "शासकीय भूलेख व सातबारा नोंदींचे स्वयंचलित प्रमाणीकरण.",
    feat3Title: "डिजिटल गुणवत्ता तपासणी",
    feat3Desc: "ओलावा आणि गुणवत्तेची डिजिटल तपासणी आणि थेट रांग स्थिती.",
    feat4Title: "डिजिटल जे-फॉर्म व डीबीटी",
    feat4Desc: "तात्काळ डिजिटल पावती आणि थेट बँक खात्यात पैसे जमा.",
    farmer: "शेतकरी",
    official: "शासकीय अधिकारी",
    farmerSignIn: "शेतकरी साइन इन",
    newRegistration: "नवीन नोंदणी",
    mobileNumber: "मोबाईल नंबर",
    password: "पासवर्ड",
    signInBtn: "साइन इन करा",
    quickAccess: "त्वरित प्रवेश",
    quickRoleShortcuts: "भूमिका शॉर्टकट",
    quickFarmerDemo: "शेतकरी (रमेश कुमार) म्हणून त्वरित लॉगिन",
    officialRole: "अधिकारी पद",
    selectOfficialRole: "अधिकारी पद निवडा",
    adminRole: "राज्य प्रशासक",
    centreAdminRole: "केंद्र प्रशासक",
    checkinRole: "चेक-इन अधिकारी",
    qualityRole: "गुणवत्ता तपासणी अधिकारी",
    weighingRole: "वजन अधिकारी",
    assignedCentre: "नियुक्त खरेदी केंद्र",
    officerId: "अधिकारी आयडी",
    welcome: "स्वागत आहे",
    switchRole: "लॉग आउट / पद बदला",
    overview: "माझी प्रोफाइल",
    myProfile: "माझी प्रोफाइल",
    bookSlot: "स्लॉट बुक करा",
    landRecords: "जमीन नोंदी",
    liveQueue: "थेट रांग स्थिती",
    receipts: "खरेदी पावत्या",
    activeBooking: "सक्रिय खरेदी अपॉइंटमेंट",
    cancelBooking: "बुकिंग रद्द करा",
    trackProgress: "प्रगती पहा",
    digitalPass: "डिजिटल चेक-इन पास",
    cropAndSeason: "पीक आणि हंगाम",
    expectedQty: "अपेक्षित वजन",
    procurementCentre: "खरेदी केंद्र",
    appointmentTime: "अपॉइंटमेंट वेळ",
    dailyCapacity: "दैनंदिन क्षमता",
    verifiedArea: "प्रमाणित जमीन क्षेत्र",
    activeMsp: "सध्याचा हमीभाव (MSP)",
    verified: "प्रमाणित",
    pending: "प्रलंबित",
    enterAadhaar: "१२ अंकी आधार क्रमांक प्रविष्ट करा",
    sendOtp: "ओटीपी पाठवा",
    enterOtp: "४ अंकी ओटीपी टाका",
    verifyOtp: "ओटीपी तपासा",
    completeReg: "नोंदणी पूर्ण करून लॉगिन करा",
    home: "मुख्यपृष्ठ",
    slotBooking: "स्लॉट बुकिंग",
    liveReport: "थेट अहवाल",
    bookingHistory: "बुकिंग इतिहास",
    procurements: "पीक खरेदी",
    helpSupport: "मदत व सहाय्य",
    alerts: "सूचना",
    upcomingProcurement: "आगामी खरेदी",
    services: "सेवा",
    viewDetails: "तपशील पहा",
    noActiveBooking: "कोणतीही सक्रिय बुकिंग नाही!",
    bookSlotNow: "आता स्लॉट बुक करा",
    welcomeBack: "पुन्हा स्वागत आहे",
    notificationsAndAlerts: "सूचना व अद्यतने",
    close: "बंद करा",
    cancel: "रद्द करा",
    confirmCancel: "रद्द करण्याची पुष्टी करा",
    logoutConfirmTitle: "लॉग आउट पुष्टी करा",
    logoutConfirmDesc: "आपण खरोखर आपल्या किसानसेतू खात्यातून लॉग आउट करू इच्छिता?",
    selectLanguage: "भाषा निवडा",
    personalDetails: "वैयक्तिक आणि ओळख तपशील",
    residentialAddress: "निवासाचा पत्ता",
    verifiedParcels: "प्रमाणित सातबारा गट",
    liveQueueHeading: "थेट मंडी खरेदी रांग",
    bookingHistoryHeading: "आपला अपॉइंटमेंट इतिहास",
    procurementHeading: "खरेदी प्रमाणपत्रे व जे-फॉर्म",
    contactSupport: "मदत कक्ष व सहाय्य",
    allAppointments: "सर्व अपॉइंटमेंट्स",
    queueAndDbt: "रांग व डीबीटी स्थिती",
    cadastralParcels: "जमीन सातबारा तपशील",
    aadhaarAndBank: "आधार व बँक माहिती",
    formJReceipts: "जे-फॉर्म डिजिटल पावत्या",
    tollFreeAndGuide: "टोल-फ्री व मार्गदर्शक"
  },
  ta: {
    appName: "கிசான்சேது",
    tagline: "மையப்படுத்தப்பட்ட பயிர் கொள்முதல் மற்றும் திறன் அடிப்படையிலான முன்பதிவு தளம்",
    heroTitle1: "மையப்படுத்தப்பட்ட பயிர் கொள்முதல் &",
    heroTitle2: "திறன் அடிப்படையிலான முன்பதிவு",
    heroDesc: "நேரடி முன்பதிவு, தர ஆய்வு மற்றும் நேரடி வங்கி பணப்பரிமாற்றத்துடன் நெறிப்படுத்தப்பட்ட கொள்முதல்.",
    feat1Title: "திறன் அடிப்படையிலான முன்பதிவு",
    feat1Desc: "கொள்முதல் நிலையங்களில் கூட்ட நெரிசலைத் தவிர்க்க தினசரி திறன் மேலாண்மை.",
    feat2Title: "நில ஆவணங்கள் இணைப்பு",
    feat2Desc: "அரசு ஆவணங்களுடன் தானியங்கி நில சரிபார்ப்பு.",
    feat3Title: "டிஜிட்டல் தர மதிப்பீடு",
    feat3Desc: "ஈரப்பதம் மற்றும் தூய்மை சோதனை நேரலை வரிசை.",
    feat4Title: "டிஜிட்டல் ரசீது & டிபிடி",
    feat4Desc: "உடனடி விற்பனை ரசீது மற்றும் வங்கி கணக்கில் நேரடி பணம்.",
    farmer: "விவசாயி",
    official: "துறை அதிகாரி",
    farmerSignIn: "விவசாயி உள்நுழைவு",
    newRegistration: "புதிய பதிவு",
    mobileNumber: "கைபேசி எண்",
    password: "கடவுச்சொல்",
    signInBtn: "உள்நுழைக",
    quickAccess: "விரைவு அணுகல்",
    quickRoleShortcuts: "அதிகாரிகள் பட்டியல்",
    quickFarmerDemo: "விவசாயி (ரமேஷ் குமார்) நேரடி உள்நுழைவு",
    officialRole: "அதிகாரி பதவி",
    selectOfficialRole: "அதிகாரி பதவியைத் தேர்ந்தெடுக்கவும்",
    adminRole: "மாநில நிர்வாகி",
    centreAdminRole: "மைய நிர்வாகி",
    checkinRole: "சரிபார்ப்பு அதிகாரி",
    qualityRole: "தர பரிசோதனை அதிகாரி",
    weighingRole: "எடை பரிசோதகர்",
    assignedCentre: "ஒதுக்கப்பட்ட கொள்முதல் மையம்",
    officerId: "அதிகாரி ஐடி",
    welcome: "நல்வரவு",
    switchRole: "வெளியேறு / பதவி மாற்று",
    overview: "என் சுயவிவரம்",
    myProfile: "என் சுயவிவரம்",
    bookSlot: "முன்பதிவு செய்க",
    landRecords: "நில விவரங்கள்",
    liveQueue: "நேரலை வரிசை நிலை",
    receipts: "கொள்முதல் ரசீதுகள்",
    activeBooking: "நடப்பு முன்பதிவு",
    cancelBooking: "முன்பதிவை ரத்து செய்க",
    trackProgress: "நிலையை கண்காணிக்க",
    digitalPass: "டிஜிட்டல் பாஸ்",
    cropAndSeason: "பயிர் & பருவம்",
    expectedQty: "எதிர்பார்க்கப்படும் அளவு",
    procurementCentre: "கொள்முதல் மையம்",
    appointmentTime: "நேரம்",
    dailyCapacity: "தினசரி திறன்",
    verifiedArea: "சரிபார்க்கப்பட்ட நிலம்",
    activeMsp: "அரசு நிர்ணய விலை",
    verified: "சரிபார்க்கப்பட்டது",
    pending: "நிலுவையில் உள்ளது",
    enterAadhaar: "12 இலக்க ஆதார் எண்",
    sendOtp: "OTP அனுப்புக",
    enterOtp: "OTP உள்ளிடவும்",
    verifyOtp: "சரிபார்க்கவும்",
    completeReg: "பதிவை முடித்து உள்நுழையவும்",
    home: "முகப்பு",
    slotBooking: "ஸ்லாட் முன்பதிவு",
    liveReport: "நேரடி அறிக்கை",
    bookingHistory: "முன்பதிவு வரலாறு",
    procurements: "கொள்முதல்",
    helpSupport: "உதவி & ஆதரவு",
    alerts: "அறிவிப்புகள்",
    upcomingProcurement: "வரவிருக்கும் கொள்முதல்",
    services: "சேவைகள்",
    viewDetails: "விவரங்களைக் காண்க",
    noActiveBooking: "முன்பதிவு எதுவும் இல்லை!",
    bookSlotNow: "இப்போது ஸ்லாட் முன்பதிவு செய்யவும்",
    welcomeBack: "மீண்டும் வருக",
    notificationsAndAlerts: "அறிவிப்புகள் & எச்சரிக்கைகள்",
    close: "மூடு",
    cancel: "ரத்து செய்",
    confirmCancel: "ரத்துசெய்வதை உறுதிப்படுத்தவும்",
    logoutConfirmTitle: "வெளியேறுதலை உறுதிப்படுத்தவும்",
    logoutConfirmDesc: "உங்கள் கிசான்சேது கணக்கிலிருந்து வெளியேற விரும்புகிறீர்களா?",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    personalDetails: "தனிப்பட்ட & அடையாள விவரங்கள்",
    residentialAddress: "முகவரி விவரங்கள்",
    verifiedParcels: "சரிபார்க்கப்பட்ட நிலங்கள்",
    liveQueueHeading: "நேரடி கொள்முதல் வரிசை",
    bookingHistoryHeading: "உங்கள் முன்பதிவு வரலாறு",
    procurementHeading: "கொள்முதல் சான்றிதழ்கள்",
    contactSupport: "உதவி மையம் & ஆதரவு",
    allAppointments: "அனைத்து முன்பதிவுகள்",
    queueAndDbt: "வரிசை & டிபிடி நிலை",
    cadastralParcels: "நில விவரங்கள்",
    aadhaarAndBank: "ஆதார் & வங்கி விவரங்கள்",
    formJReceipts: "டிஜிட்டல் ரசீதுகள்",
    tollFreeAndGuide: "உதவி எண்கள் & வழிகாட்டி"
  },
  gu: {
    appName: "કિસાનસેતુ",
    tagline: "કેન્દ્રીયકૃત પાક ખરીદી અને ક્ષમતા-આધારિત સ્લોટ બુકિંગ પ્લેટફોર્મ",
    heroTitle1: "કેન્દ્રીયકૃત પાક ખરીદી અને",
    heroTitle2: "ક્ષમતા-આધારિત સ્લોટ બુકિંગ",
    heroDesc: "પારદર્શક સ્લોટ બુકિંગ, ડિજિટલ ગુણવત્તા ચકાસણી અને સીધા બેંક ખાતામાં PFMS પેમેન્ટ.",
    feat1Title: "ક્ષમતા-આધારિત બુકિંગ",
    feat1Desc: "માર્કેટ યાર્ડમાં ભીડ રોકવા માટે દૈનિક ક્ષમતા મુજબ સ્લોટ ફાળવણી.",
    feat2Title: "એગ્રીસ્ટેક અને જમીન રેકોર્ડ",
    feat2Desc: "સરકારી રેકોર્ડ્સમાંથી જમીન અને પાકની વિગતોની સ્વચાલિત ચકાસણી.",
    feat3Title: "ડિજિટલ ગુણવત્તા ગ્રેડિંગ",
    feat3Desc: "ભેજ અને શુદ્ધતાની ડિજિટલ ચકાસણી સાથે લાઇવ કતાર સ્થિતિ.",
    feat4Title: "ડિજિટલ જે-ફોર્મ અને ડીબીટી",
    feat4Desc: "ત્વરિત ડિજિટલ રસીદ અને ખેડૂતના ખાતામાં સીધી ચુકવણી.",
    farmer: "ખેડૂત",
    official: "વિભાગીય અધિકારી",
    farmerSignIn: "ખેડૂત સાઇન ઇન",
    newRegistration: "નવી નોંધણી",
    mobileNumber: "મોબાઇલ નંબર",
    password: "પાસવર્ડ",
    signInBtn: "સાઇન ઇન કરો",
    quickAccess: "ઝડપી પ્રવેશ",
    quickRoleShortcuts: "અધિકારી શોર્ટકટ",
    quickFarmerDemo: "ખેડૂત (રમેશ કુમાર) તરીકે લોગિન",
    officialRole: "અધિકારી પદ",
    selectOfficialRole: "અધિકારી પદ પસંદ કરો",
    adminRole: "રાજ્ય એડમિનિસ્ટ્રેટર",
    centreAdminRole: "કેન્દ્ર એડમિન",
    checkinRole: "ચેક-ઇન અધિકારી",
    qualityRole: "ગુણવત્તા તપાસ અધિકારી",
    weighingRole: "તોલમાપ અધિકારી",
    assignedCentre: "નિયુક્ત ખરીદ કેન્દ્ર",
    officerId: "અધિકારી આઈડી",
    welcome: "સ્વાગત છે",
    switchRole: "લૉગ આઉટ / ભૂમિકા બદલો",
    overview: "મારી પ્રોફાઇલ",
    myProfile: "મારી પ્રોફાઇલ",
    bookSlot: "સ્લોટ બુક કરો",
    landRecords: "જમીન રેકોર્ડ",
    liveQueue: "લાઇવ કતાર સ્થિતિ",
    receipts: "ખરીદી રસીદ",
    activeBooking: "સક્રિય બુકિંગ",
    cancelBooking: "બુકિંગ રદ કરો",
    trackProgress: "પ્રગતિ ટ્રેક કરો",
    digitalPass: "ડિજિટલ ચેક-ઇન પાસ",
    cropAndSeason: "પાક અને સીઝન",
    expectedQty: "અપેક્ષિત વજન",
    procurementCentre: "ખરીદ કેન્દ્ર",
    appointmentTime: "સમય",
    dailyCapacity: "દૈનિક ક્ષમતા",
    verifiedArea: "ચકાસાયેલ જમીન",
    activeMsp: "હાલનો ટેકાનો ભાવ",
    verified: "ચકાસાયેલ",
    pending: "બાકી",
    enterAadhaar: "૧૨ અંકનો આધાર નંબર દાખલ કરો",
    sendOtp: "ઓટીપી મોકલો",
    enterOtp: "૪ અંકનો ઓટીપી દાખલ કરો",
    verifyOtp: "ઓટીપી ચકાસો",
    completeReg: "નોંધણી પૂર્ણ કરો અને લોગિન કરો",
    home: "હોમ",
    slotBooking: "સ્લોટ બુકિંગ",
    liveReport: "લાઇવ રિપોર્ટ",
    bookingHistory: "બુકિંગ ઇતિહાસ",
    procurements: "પાક ખરીદી",
    helpSupport: "મદદ અને સપોર્ટ",
    alerts: "સૂચનાઓ",
    upcomingProcurement: "આગામી ખરીદી",
    services: "સેવાઓ",
    viewDetails: "વિગતો જુઓ",
    noActiveBooking: "કોઈ સક્રિય બુકિંગ નથી!",
    bookSlotNow: "હમણાં જ સ્લોટ બુક કરો",
    welcomeBack: "પાછા સ્વાગત છે",
    notificationsAndAlerts: "સૂચનાઓ અને ચેતવણીઓ",
    close: "બંધ કરો",
    cancel: "રદ કરો",
    confirmCancel: "રદ કરવાની પુષ્ટિ કરો",
    logoutConfirmTitle: "લૉગ આઉટ ખાતરી કરો",
    logoutConfirmDesc: "શું તમે ખરેખર તમારા કિસાનસેતુ ખાતામાંથી લૉગ આઉટ કરવા માંગો છો?",
    selectLanguage: "ભાષા પસંદ કરો",
    personalDetails: "વ્યક્તિગત અને ઓળખ વિગતો",
    residentialAddress: "રહેઠાણનું સરનામું",
    verifiedParcels: "ચકાસાયેલ જમીન ખાતાઓ",
    liveQueueHeading: "લાઇવ મંડી ખરીદ કતાર",
    bookingHistoryHeading: "તમારો અપોઇન્ટમેન્ટ ઇતિહાસ",
    procurementHeading: "ખરીદી પ્રમાણપત્રો અને જે-ફોર્મ",
    contactSupport: "સહાયતા કેન્દ્ર અને સપોર્ટ",
    allAppointments: "તમામ અપોઇન્ટમેન્ટ્સ",
    queueAndDbt: "કતાર અને ડીબીટી સ્થિતિ",
    cadastralParcels: "જમીન ખાતાની વિગતો",
    aadhaarAndBank: "આધાર અને બેંક વિગતો",
    formJReceipts: "જે-ફોર્મ ડિજિટલ રસીદો",
    tollFreeAndGuide: "ટોલ-ફ્રી અને માર્ગદર્શિકા"
  },
  pa: {
    appName: "ਕਿਸਾਨਸਾਥੀ",
    tagline: "ਕੇਂਦਰੀਕ੍ਰਿਤ ਫਸਲ ਖਰੀਦ ਅਤੇ ਸਮਰੱਥਾ-ਅਧਾਰਿਤ ਸਲਾਟ ਬੁਕਿੰਗ ਪਲੇਟਫਾਰਮ",
    heroTitle1: "ਕੇਂਦਰੀਕ੍ਰਿਤ ਫਸਲ ਖਰੀਦ ਅਤੇ",
    heroTitle2: "ਸਮਰੱਥਾ-ਅਧਾਰਿਤ ਸਮਾਂ-ਸਾਰਣੀ",
    heroDesc: "ਪਾਰਦਰਸ਼ੀ ਸਲਾਟ ਬੁਕਿੰਗ, ਡਿਜੀਟਲ ਗੁਣਵੱਤਾ ਜਾਂਚ ਅਤੇ ਸਿੱਧੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ PFMS ਰਾਹੀਂ ਭੁਗਤਾਨ।",
    feat1Title: "ਸਮਰੱਥਾ-ਅਧਾਰਿਤ ਬੁਕਿੰਗ",
    feat1Desc: "ਮੰਡੀ ਵਿੱਚ ਭੀੜ ਰੋਕਣ ਲਈ ਰੋਜ਼ਾਨਾ ਸਮਰੱਥਾ ਅਨੁਸਾਰ ਸਲਾਟ ਵੰਡ।",
    feat2Title: "ਜ਼ਮੀਨੀ ਰਿਕਾਰਡ ਤਸਦੀਕ",
    feat2Desc: "ਸਰਕਾਰੀ ਰਿਕਾਰਡ ਤੋਂ ਜ਼ਮੀਨ ਅਤੇ ਫਸਲ ਦੇ ਵੇਰਵਿਆਂ ਦੀ ਆਟੋਮੈਟਿਕ ਪੁਸ਼ਟੀ।",
    feat3Title: "ਡਿਜੀਟਲ ਕੁਆਲਿਟੀ ਗਰੇਡਿੰਗ",
    feat3Desc: "ਨਮੀ ਅਤੇ ਸ਼ੁੱਧਤਾ ਦੀ ਜਾਂਚ ਨਾਲ ਲਾਈਵ ਕਤਾਰ ਦੀ ਸਥਿਤੀ।",
    feat4Title: "ਡਿਜੀਟਲ ਜੇ-ਫਾਰਮ ਅਤੇ ਡੀਬੀਟੀ",
    feat4Desc: "ਤੁਰੰਤ ਡਿਜੀਟਲ ਖਰੀਦ ਰਸੀਦ ਅਤੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਸਿੱਧਾ ਭੁਗਤਾਨ।",
    farmer: "ਕਿਸਾਨ",
    official: "ਵਿਭਾਗੀ ਅਧਿਕਾਰੀ",
    farmerSignIn: "ਕਿਸਾਨ ਸਾਈਨ ਇਨ",
    newRegistration: "ਨਵੀਂ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    mobileNumber: "ਮੋਬਾਈਲ ਨੰਬਰ",
    password: "ਪਾਸਵਰਡ",
    signInBtn: "ਸਾਈਨ ਇਨ ਕਰੋ",
    quickAccess: "ਤੁਰੰਤ ਪਹੁੰਚ",
    quickRoleShortcuts: "ਅਧਿਕਾਰਤ ਸ਼ਾਰਟਕੱਟ",
    quickFarmerDemo: "ਕਿਸਾਨ (ਰਮੇਸ਼ ਕੁਮਾਰ) ਵਜੋਂ ਲੌਗਇਨ",
    officialRole: "ਅਧਿਕਾਰੀ ਦਾ ਅਹੁਦਾ",
    selectOfficialRole: "ਅਧਿਕਾਰੀ ਦਾ ਅਹੁਦਾ ਚੁਣੋ",
    adminRole: "ਰਾਜ ਪ੍ਰਸ਼ਾਸਕ",
    centreAdminRole: "ਕੇਂਦਰ ਪ੍ਰਸ਼ਾਸਕ",
    checkinRole: "ਚੈੱਕ-ਇਨ ਅਧਿਕਾਰੀ",
    qualityRole: "ਕੁਆਲਿਟੀ ਚੈੱਕ ਅਧਿਕਾਰੀ",
    weighingRole: "ਤੋਲ ਅਧਿਕਾਰੀ",
    assignedCentre: "ਅਲਾਟ ਕੀਤਾ ਖਰੀਦ ਕੇਂਦਰ",
    officerId: "ਅਧਿਕਾਰੀ ਆਈਡੀ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    switchRole: "ਲੌਗ ਆਉਟ",
    overview: "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
    myProfile: "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
    bookSlot: "ਸਲਾਟ ਬੁੱਕ ਕਰੋ",
    landRecords: "ਜ਼ਮੀਨ ਦਾ ਰਿਕਾਰਡ",
    liveQueue: "ਲਾਈਵ ਕਤਾਰ ਸਥਿਤੀ",
    receipts: "ਖਰੀਦ ਰਸੀਦਾਂ",
    activeBooking: "ਚੱਲ ਰਹੀ ਬੁਕਿੰਗ",
    cancelBooking: "ਬੁਕਿੰਗ ਰੱਦ ਕਰੋ",
    trackProgress: "ਸਥਿਤੀ ਦੇਖੋ",
    digitalPass: "ਡਿਜੀਟਲ ਪਾਸ",
    cropAndSeason: "ਫਸਲ ਅਤੇ ਸੀਜ਼ਨ",
    expectedQty: "ਅੰਦਾਜ਼ਨ ਮਾਤਰਾ",
    procurementCentre: "ਖਰੀਦ ਕੇਂਦਰ",
    appointmentTime: "ਨਿਯਤ ਸਮਾਂ",
    dailyCapacity: "ਰੋਜ਼ਾਨਾ ਸਮਰੱਥਾ",
    verifiedArea: "ਤਸਦੀਕਸ਼ੁਦਾ ਰਕਬਾ",
    activeMsp: "ਮੌਜੂਦਾ ਐਮਐਸਪੀ (MSP)",
    verified: "ਤਸਦੀਕ ਕੀਤਾ",
    pending: "ਬਕਾਇਆ",
    enterAadhaar: "12 ਅੰਕਾਂ ਦਾ ਆਧਾਰ ਨੰਬਰ ਭਰੋ",
    sendOtp: "ਓਟੀਪੀ ਭੇਜੋ",
    enterOtp: "ਓਟੀਪੀ ਦਰਜ ਕਰੋ",
    verifyOtp: "ਓਟੀਪੀ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    completeReg: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰਕੇ ਲੌਗਇਨ ਕਰੋ",
    home: "ਮੁੱਖ ਪੰਨਾ",
    slotBooking: "ਸਲਾਟ ਬੁਕਿੰਗ",
    liveReport: "ਲਾਈਵ ਮੰਡੀ ਰਿਪੋਰਟ",
    bookingHistory: "ਬੁਕਿੰਗ ਇਤਿਹਾਸ",
    procurements: "ਉਪਜ ਖਰੀਦ",
    helpSupport: "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",
    alerts: "ਸੂਚਨਾਵਾਂ",
    upcomingProcurement: "ਆਗਾਮੀ ਖਰੀਦ",
    services: "ਸੇਵਾਵਾਂ",
    viewDetails: "ਵੇਰਵੇ ਦੇਖੋ",
    noActiveBooking: "ਕੋਈ ਸਰਗਰਮ ਬੁਕਿੰਗ ਨਹੀਂ ਹੈ!",
    bookSlotNow: "ਹੁਣੇ ਸਲਾਟ ਬੁੱਕ ਕਰੋ",
    welcomeBack: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ",
    notificationsAndAlerts: "ਸੂਚਨਾਵਾਂ ਅਤੇ ਅਲਰਟ",
    close: "ਬੰਦ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    confirmCancel: "ਰੱਦ ਕਰਨ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    logoutConfirmTitle: "ਲੌਗ ਆਉਟ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    logoutConfirmDesc: "ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਆਪਣੇ ਕਿਸਾਨਸਾਥੀ ਖਾਤੇ ਤੋਂ ਲੌਗ ਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    personalDetails: "ਨਿੱਜੀ ਅਤੇ ਪਛਾਣ ਵੇਰਵੇ",
    residentialAddress: "ਰਿਹਾਇਸ਼ੀ ਪਤਾ",
    verifiedParcels: "ਤਸਦੀਕਸ਼ੁਦਾ ਜ਼ਮੀਨ ਖਸਰਾ",
    liveQueueHeading: "ਲਾਈਵ ਮੰਡੀ ਖਰੀਦ ਕਤਾਰ",
    bookingHistoryHeading: "ਤੁਹਾਡਾ ਅਪਾਇੰਟਮੈਂਟ ਇਤਿਹਾਸ",
    procurementHeading: "ਖਰੀਦ ਸਰਟੀਫਿਕੇਟ ਅਤੇ ਜੇ-ਫਾਰਮ",
    contactSupport: "ਸਹਾਇਤਾ ਕੇਂਦਰ ਅਤੇ ਹੈਲਪਡੈਸਕ",
    allAppointments: "ਸਾਰੇ ਅਪਾਇੰਟਮੈਂਟ",
    queueAndDbt: "ਕਤਾਰ ਅਤੇ ਡੀਬੀਟੀ ਸਥਿਤੀ",
    cadastralParcels: "ਜ਼ਮੀਨ ਖਸਰਾ ਵੇਰਵੇ",
    aadhaarAndBank: "ਆਧਾਰ ਅਤੇ ਬੈਂਕ ਵੇਰਵੇ",
    formJReceipts: "ਜੇ-ਫਾਰਮ ਡਿਜੀਟਲ ਰਸੀਦਾਂ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    resetPassword: "ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ",
    resetPasswordDesc: "ਆਪਣਾ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਜਾਂ ਅਧਿਕਾਰੀ ਆਈਡੀ ਦਰਜ ਕਰੋ।",
    enterOtp: "ਓਟੀਪੀ ਦਰਜ ਕਰੋ",
    newPassword: "ਨਵਾਂ ਪਾਸਵਰਡ",
    confirmNewPassword: "ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    enterNewPassword: "ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
    reEnterNewPassword: "ਨਵਾਂ ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਦਰਜ ਕਰੋ",
    submitAndUpdatePassword: "ਪਾਸਵਰਡ ਸਬਮਿਟ ਅਤੇ ਅੱਪਡੇਟ ਕਰੋ",
    updatingPassword: "ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਹੋ ਰਿਹਾ ਹੈ...",
    sendOtp: "ਓਟੀਪੀ ਭੇਜੋ",
    sendingOtp: "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    resendOtp: "ਓਟੀਪੀ ਮੁੜ ਭੇਜੋ",
    enterTenDigitMobile: "10-ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    enterOfficerIdOrMobile: "ਅਧਿਕਾਰੀ ਆਈਡੀ / ਮੋਬਾਈਲ ਦਰਜ ਕਰੋ",
    otpSentSuccess: "ਐਸਐਮਐਸ ਰਾਹੀਂ ਤਸਦੀਕੀ ਓਟੀਪੀ ਭੇਜਿਆ ਗਿਆ",
    passwordResetSuccess: "ਪਾਸਵਰਡ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋ ਗਿਆ! ਹੁਣ ਤੁਸੀਂ ਸਾਈਨ ਇਨ ਕਰ ਸਕਦੇ ਹੋ।",
    passwordResetFailed: "ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਓਟੀਪੀ ਜਾਂਚੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    registeredMobileNumber: "ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ",
    officerIdOrMobile: "ਅਧਿਕਾਰੀ ਆਈਡੀ / ਮੋਬਾਈਲ",
    newFarmerCreateAccount: "ਨਵਾਂ ਕਿਸਾਨ ਖਾਤਾ ਬਣਾਓ",
    backToSignIn: "ਸਾਈਨ ਇਨ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    farmerRegistrationTitle: "ਨਵਾਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    hello: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    dbtBankAccount: "PFMS ਸਿੱਧਾ ਲਾਭ ਅੰਤਰਣ (DBT) ਬੈਂਕ ਖਾਤਾ",
    updateAddBank: "ਬੈਂਕ ਖਾਤਾ ਅੱਪਡੇਟ ਕਰੋ / ਜੋੜੋ",
    updateContact: "ਸੰਪਰਕ ਵੇਰਵੇ ਅੱਪਡੇਟ ਕਰੋ",
    updatePassword: "ਪਾਸਵਰਡ ਬਦਲੋ",
    farmerName: "ਕਿਸਾਨ ਦਾ ਨਾਮ",
    fatherName: "ਪਿਤਾ ਦਾ ਨਾਮ",
    age: "ਉਮਰ",
    ageGender: "ਉਮਰ / ਲਿੰਗ",
    aadhaarCardNumber: "ਆਧਾਰ ਕਾਰਡ ਨੰਬਰ",
    primaryMobile: "ਮੁੱਖ ਮੋਬਾਈਲ ਨੰਬਰ",
    emailAddress: "ਈਮੇਲ ਪਤਾ",
    permanentAddress: "ਪੱਕਾ ਪਤਾ",
    villageTehsil: "ਪਿੰਡ ਅਤੇ ਤਹਿਸੀਲ",
    districtState: "ਜ਼ਿਲ੍ਹਾ ਅਤੇ ਰਾਜ",
    agriZone: "ਖੇਤੀਬਾੜੀ ਜ਼ੋਨ",
    registryVerification: "ਰਜਿਸਟਰੀ ਤਸਦੀਕ",
    linked: "ਲਿੰਕ ਕੀਤਾ ਗਿਆ",
    verifiedUidai: "UIDAI ਤਸਦੀਕਸ਼ੁਦਾ",
    aadhaarAgriVerified: "ਆਧਾਰ ਈ-ਕੇਵਾਈਸੀ ਅਤੇ ਐਗਰੀਸਟੈਕ ਤਸਦੀਕਸ਼ੁਦਾ",
    bankAccount: "ਬੈਂਕ ਖਾਤਾ",
    bankName: "ਬੈਂਕ ਦਾ ਨਾਮ",
    accountNumber: "ਖਾਤਾ ਨੰਬਰ",
    ifscCode: "IFSC ਕੋਡ",
    branchName: "ਸ਼ਾਖਾ ਦਾ ਨਾਮ",
    accountHolder: "ਖਾਤਾ ਧਾਰਕ ਦਾ ਨਾਮ",
    primaryDbtBank: "ਮੁੱਖ DBT ਭੁਗਤਾਨ ਬੈਂਕ",
    dbtStatus: "DBT ਸਥਿਤੀ",
    activeDbtSeeded: "ਸਰਗਰਮ ਅਤੇ PFMS ਸੀਡ ਕੀਤਾ ਹੋਇਆ",
    agriCadastreEyebrow: "ਐਗਰੀਕੈਡਾਸਟਰ ਅਤੇ ਐਗਰੀਸਟੈਕ",
    agriCadastreDesc: "ਕੇਂਦਰੀਕ੍ਰਿਤ ਭੂਲੇਖ ਅਤੇ ਐਗਰੀਸਟੈਕ ਤੋਂ ਤਸਦੀਕਸ਼ੁਦਾ ਖਸਰਾ ਵੇਰਵੇ।",
    syncAgriStack: "ਐਗਰੀਸਟੈਕ ਸਿੰਕ ਕਰੋ",
    syncingAgriStack: "ਐਗਰੀਸਟੈਕ ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...",
    addLand: "ਜ਼ਮੀਨ ਜੋੜੋ",
    khasraNoHeader: "ਖਸਰਾ ਨੰ.",
    villageTehsilHeader: "ਪਿੰਡ ਅਤੇ ਤਹਿਸੀਲ",
    districtHeader: "ਜ਼ਿਲ੍ਹਾ",
    areaHeader: "ਰਕਬਾ",
    soilTypeHeader: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    sourceHeader: "ਸਰੋਤ",
    statusHeader: "ਸਥਿਤੀ",
    bookingEyebrow: "ਫਸਲ ਖਰੀਦ ਬੁਕਿੰਗ",
    bookingOpen: "ਬੁਕਿੰਗ ਖੁੱਲ੍ਹੀ ਹੈ",
    bookingDesc: "ਫਸਲ, ਤਸਦੀਕਸ਼ੁਦਾ ਜ਼ਮੀਨ, ਅੰਦਾਜ਼ਨ ਝਾੜ ਮਾਤਰਾ ਅਤੇ ਆਪਣੀ ਪਸੰਦ ਦਾ 20-ਮਿੰਟ ਦਾ ਸਮਾਂ ਸਲਾਟ ਚੁਣੋ।",
    tokenActive: "ਸਰਗਰਮ ਟੋਕਨ",
    cropDetailsStep: "ਫਸਲ ਦਾ ਵੇਰਵਾ",
    cropDetailsDesc: "ਆਪਣੀ ਉਪਜ ਦੀ ਫਸਲ ਚੁਣੋ",
    season: "ਮੌਸਮ (ਸੀਜ਼ਨ)",
    cropName: "ਫਸਲ ਦਾ ਨਾਮ",
    selectLandStep: "ਜ਼ਮੀਨ ਚੁਣੋ",
    selectLandDesc: "ਉਹ ਸਾਰੇ ਤਸਦੀਕਸ਼ੁਦਾ ਜ਼ਮੀਨ ਖਸਰੇ ਚੁਣੋ ਜਿੱਥੇ ਫਸਲ ਕੱਟੀ ਗਈ ਹੈ",
    expectedQtyStep: "ਅੰਦਾਜ਼ਨ ਉਪਜ ਮਾਤਰਾ",
    expectedQtyDesc: "ਸਾਰੇ ਚੁਣੇ ਖਸਰਿਆਂ ਦੀ ਕੁੱਲ ਅੰਦਾਜ਼ਨ ਉਪਜ (ਟਨ ਵਿੱਚ) ਦਰਜ ਕਰੋ।",
    expectedQtyTonnes: "ਅੰਦਾਜ਼ਨ ਮਾਤਰਾ (ਟਨ ਵਿੱਚ)",
    centreDateTimeStep: "ਕੇਂਦਰ, ਮਿਤੀ ਅਤੇ ਸਮਾਂ ਸਲਾਟ",
    centreDateTimeDesc: "ਖਰੀਦ ਕੇਂਦਰ ਅਤੇ ਆਪਣੀ ਪਸੰਦ ਦਾ ਸਮਾਂ ਸਲਾਟ ਚੁਣੋ।",
    selectTimeSlot: "ਸਮਾਂ ਸਲਾਟ ਚੁਣੋ (09:00 AM – 05:00 PM)",
    bookSlotBtn: "ਸਲਾਟ ਬੁੱਕ ਕਰੋ",
    bookingSlotBtn: "ਸਲਾਟ ਬੁੱਕ ਹੋ ਰਿਹਾ ਹੈ...",
    bookingSummary: "ਬੁਕਿੰਗ ਵੇਰਵਾ",
    selectedLands: "ਚੁਣਿਆ ਗਿਆ ਖਸਰਾ",
    expectedQtyLabel: "ਅੰਦਾਜ਼ਨ ਮਾਤਰਾ",
    centreLabel: "ਖਰੀਦ ਕੇਂਦਰ",
    dateLabel: "ਮਿਤੀ",
    timeSlotLabel: "ਸਮਾਂ ਸਲਾਟ",
    slotConfirmedNote: "ਡਿਜੀਟਲ ਪਾਸ ਦੇ ਨਾਲ ਸਲਾਟ ਅਪਾਇੰਟਮੈਂਟ ਤੁਰੰਤ ਕਨਫਰਮ ਹੋਵੇਗੀ।",
    liveTrackerEyebrow: "ਲਾਈਵ ਮੰਡੀ ਕਤਾਰ ਟਰੈਕਰ",
    liveReportDesc: "ਮੰਡੀ ਵਿੱਚ ਤੁਹਾਡੀ ਫਸਲ ਖਰੀਦ ਦੀ ਲਾਈਵ ਸਥਿਤੀ ਟਰੈਕਿੰਗ।",
    currentQueue: "ਮੌਜੂਦਾ ਕਤਾਰ",
    gatePass: "ਗੇਟ ਪਾਸ",
    procurementProcessingStages: "ਫਸਲ ਖਰੀਦ ਪ੍ਰਕਿਰਿਆ ਦੇ ਪੜਾਅ",
    stage1: "1. ਸਲਾਟ ਬੁਕਿੰਗ ਸਫਲ",
    stage2: "2. ਗੇਟ 'ਤੇ ਹਾਜ਼ਰੀ (ਚੈੱਕ-ਇਨ)",
    stage3: "3. ਗੁਣਵੱਤਾ ਜਾਂਚ ਅਤੇ ਗਰੇਡਿੰਗ",
    stage4: "4. ਕੰਡੇ 'ਤੇ ਤੋਲ",
    stage5: "5. ਫਸਲ ਖਰੀਦ ਸੰਪੰਨ",
    stage6: "6. PFMS DBT ਭੁਗਤਾਨ",
    trackPaymentBtn: "ਭੁਗਤਾਨ ਸਥਿਤੀ ਦੇਖਣ ਲਈ ਇੱਥੇ ਕਲਿੱਕ ਕਰੋ",
    historyEyebrow: "ਅਪਾਇੰਟਮੈਂਟ ਅਤੇ ਇਤਿਹਾਸ",
    historyDesc: "ਆਪਣੇ ਸਾਰੇ ਆਗਾਮੀ, ਸਰਗਰਮ ਅਤੇ ਮੁਕੰਮਲ ਹੋ ਚੁੱਕੇ ਸਲਾਟ ਅਪਾਇੰਟਮੈਂਟ ਦਾ ਵੇਰਵਾ ਦੇਖੋ।",
    viewDetailsQr: "ਵੇਰਵੇ ਅਤੇ ਕਿਊਆਰ (QR) ਦੇਖੋ",
    procurementsEyebrow: "ਖਰੀਦ ਅਤੇ ਭੁਗਤਾਨ ਰਸੀਦਾਂ",
    procurementsDesc: "ਵੇਚੀ ਗਈ ਉਪਜ, DBT ਭੁਗਤਾਨ ਅਤੇ ਅਧਿਕਾਰਤ ਡਿਜੀਟਲ ਜੇ-ਫਾਰਮ ਪ੍ਰਮਾਣ ਪੱਤਰ।",
    totalCropSold: "ਕੁੱਲ ਵੇਚੀ ਗਈ ਉਪਜ",
    totalMoneyReceived: "ਕੁੱਲ ਪ੍ਰਾਪਤ ਭੁਗਤਾਨ",
    pendingPayouts: "ਬਕਾਇਆ ਭੁਗਤਾਨ",
    totalTransactions: "ਕੁੱਲ ਲੈਣ-ਦੇਣ (ਜੇ-ਫਾਰਮ)",
    authenticatedJForms: "ਤਸਦੀਕਸ਼ੁਦਾ ਫਸਲ ਖਰੀਦ ਰਸੀਦਾਂ (ਜੇ-ਫਾਰਮ)",
    viewDownloadJForm: "ਜੇ-ਫਾਰਮ ਦੇਖੋ / ਡਾਊਨਲੋਡ ਕਰੋ"
  }
};

// Fallback helper for all languages
export function getTranslation(lang, key) {
  if (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) {
    return TRANSLATIONS[lang][key];
  }
  // Try English fallback
  if (TRANSLATIONS["en"] && TRANSLATIONS["en"][key]) {
    return TRANSLATIONS["en"][key];
  }
  return key;
}


export const ALL_INDIAN_STATES_DATA = {
  "Rajasthan": {
    "Alwar": {
      "Kherli": ["Kherli Kalan", "Madhogarh", "Samaspur", "Bhilwara", "Rampura", "Salempur", "Dantawali"],
      "Kathumar": ["Kathumar Town", "Ronsi", "Sonkh", "Bhadokhar", "Kalyanpur", "Jatana", "Khedli"],
      "Laxmangarh": ["Laxmangarh Rural", "Badod", "Bhanokhar", "Khilora", "Harsana", "Malikpur"],
      "Ramgarh": ["Ramgarh City", "Naugaon", "Alavada", "Baghor", "Chidwa", "Kishangarh"],
      "Behror": ["Behror Urban", "Kodar", "Bardod", "Gandala", "Rewari Road", "Majri"],
      "Tijara": ["Tijara City", "Tapukara", "Bhiwadi Rural", "Kotkasim", "Sanoli"],
      "Rajgarh": ["Rajgarh Rural", "Machari", "Tehla", "Pratapgarh", "Ajabgarh"]
    },
    "Jaipur": {
      "Sanganer": ["Sanganer Rural", "Sitapura", "Watika", "Goner", "Bilwa", "Muhana", "Shivdaspura"],
      "Chomu": ["Chomu Central", "Morija", "Harsoli", "Singod", "Samod", "Kishanpura"],
      "Amer": ["Amer Rural", "Kukas", "Chandwaji", "Achrol", "Labana", "Kalyanpura"],
      "Phulera": ["Sambhar", "Renwal", "Jobner", "Bhojpura", "Dudu Rural"],
      "Kotputli": ["Kotputli Urban", "Paota", "Bansur Border", "Paniyala", "Gori"],
      "Chaksu": ["Chaksu Town", "Kothun", "Shivsinghpura", "Nimera", "Garood"],
      "Bassi": ["Bassi Rural", "Tunga", "Kanota", "Banskho", "Rohini"]
    },
    "Dausa": {
      "Lalsot": ["Lalsot Rural", "Mandawari", "Rahukwas", "Didwana", "Kalyanpura", "Binori"],
      "Bandikui": ["Bandikui Town", "Baswa", "Gular", "Kalyanpura", "Abhaneri", "Panditpura"],
      "Dausa Sadar": ["Dausa Khurd", "Bhandarej", "Khurd", "Sainthal", "Lawain"],
      "Mahwa": ["Mahwa Rural", "Kherla", "Balghat", "Bhadrawali", "Salempur"],
      "Sikrai": ["Sikrai Town", "Manpur", "Geejgarh", "Bhandari", "Kalikhar"]
    },
    "Bharatpur": {
      "Deeg": ["Deeg Rural", "Kumher", "Janu", "Bedham", "Kaman", "Pahari"],
      "Bayana": ["Bayana Town", "Brahmbad", "Farso", "Khareri", "Rupbas"],
      "Nadbai": ["Nadbai City", "Kherli Gurjar", "Barol", "Pingora", "Aron"],
      "Weir": ["Weir Rural", "Bhusawar", "Halena", "Itamada", "Kalyanpur"],
      "Nagar": ["Nagar Town", "Sikri", "Jalalpur", "Gulpara", "Kalyan"]
    },
    "Sikar": {
      "Fatehpur": ["Fatehpur Shekhawati", "Beswa", "Dhanuri", "Garinda", "Hameedpura"],
      "Laxmangarh": ["Laxmangarh Rural", "Nechhwa", "Jassu Ka Bas", "Rol", "Singod"],
      "Danta Ramgarh": ["Danta", "Ramgarh", "Khandela", "Palsana", "Losal"],
      "Neem Ka Thana": ["Neem Ka Thana Urban", "Patan", "Chetawala", "Guhala"],
      "Sri Madhopur": ["Sri Madhopur Town", "Mundru", "Kanwat", "Khandela Rural"]
    },
    "Ajmer": {
      "Kishangarh": ["Madanganj", "Harmara", "Silora", "Bandarsindri", "Rupangarh"],
      "Beawar": ["Beawar Rural", "Masuda", "Jawaja", "Sheopura", "Sendra"],
      "Nasirabad": ["Nasirabad Cantonment", "Derathu", "Shrinagar", "Loharwara"],
      "Kekri": ["Kekri Urban", "Sarwar", "Sawariya", "Kadera", "Bhinai"]
    },
    "Bikaner": {
      "Nokha": ["Nokha Mandi", "Jasrasar", "Bheenasar", "Bikampur", "Panchu"],
      "Lunkaransar": ["Lunkaransar Town", "Kalu", "Malkisar", "Mahajan", "Dharnok"],
      "Kolayat": ["Kolayat Rural", "Bajju", "Gajner", "Hadda", "Diya"],
      "Khajuwala": ["Khajuwala Mandi", "Dantor", "Chhatargarh", "Beriyawali"]
    },
    "Jodhpur": {
      "Osian": ["Osian Rural", "Balesar", "Tiwari", "Mathania", "Cherai"],
      "Bilara": ["Bilara Mandi", "Piparcity", "Bhopalgarh", "Kaparda", "Borunda"],
      "Phalodi": ["Phalodi Urban", "Bap", "Lohawat", "Aau", "Chadi"],
      "Luni": ["Luni Rural", "Salawas", "Dhandhaniya", "Rohat Road"]
    },
    "Kota": {
      "Ramganj Mandi": ["Ramganj Mandi Town", "Suket", "Chechat", "Modak", "Kherabad"],
      "Sangod": ["Sangod Town", "Kanwas", "Bapawar", "Dhudhala", "Mandap"],
      "Digod": ["Sultanpur", "Digod Rural", "Ayana", "Notana", "Kasganj"],
      "Ladpura": ["Ladpura Rural", "Mandana", "Ranpur", "Dhanodi"]
    },
    "Udaipur": {
      "Vallabhnagar": ["Bhindar", "Kanor", "Menar", "Dungla", "Kheroda"],
      "Mavli": ["Mavli Town", "Fatehnagar", "Sanwar", "Ghasiyar", "Thamla"],
      "Salumber": ["Salumber Urban", "Jhadol", "Sarada", "Semari", "Dhariyawad"],
      "Gogunda": ["Gogunda Rural", "Sayra", "Jaswantgarh", "Pindwara Road"]
    },
    "Bhilwara": {
      "Shahpura": ["Shahpura Town", "Phulia Kalan", " जहाजपुर Jahazpur", "Khamor"],
      "Mandalgarh": ["Mandalgarh Rural", "Beejoliya", "Kachhola", "Ladpura"],
      "Gulabpura": ["Gulabpura Mandi", "Hurda", "Rupaheli", "Badnor", "Asind"]
    },
    "Sri Ganganagar": {
      "Suratgarh": ["Suratgarh City", "Rajpura", "Pilibanga Border", "Padampur"],
      "Sadulshahar": ["Sadulshahar Mandi", "Khatsajja", "Budhwal", "Ghamurwali"],
      "Anupgarh": ["Anupgarh Town", "Gharsana", "Rawla", "Ramsinghpur"]
    },
    "Tonk": {
      "Malpura": ["Malpura Town", "Diggi", "Todaraisingh", "Lamba Harisingh"],
      "Niwai": ["Niwai Mandi", "Banewali", "Dattob", "Jhilai", "Nathdwara"],
      "Deoli": ["Deoli Rural", "Uniara", "Aliabad", "Ghad", "Nagar"]
    },
    "Nagaur": {
      "Merta": ["Merta City", "Riyan Badi", "Gotan", "Gagrana", "Padu Kalan"],
      "Didwana": ["Didwana Town", "Ladnun", "Molasar", "Kolyari", "Singrawat"],
      "Kuchaman": ["Kuchaman City", "Nawa", "Maroth", "Parbatsar", "Gachhipura"]
    },
    "Jhunjhunu": {
      "Nawalgarh": ["Nawalgarh Town", "Mukundgarh", "Parasrampura", "Dundlod"],
      "Khetri": ["Khetri Nagar", "Babai", "Gothra", "Mandrela", "Jasrapur"],
      "Chirawa": ["Chirawa Town", "Pilani", "Surajgarh", "Buhana", "Singhana"]
    },
    "Churu": {
      "Ratangarh": ["Ratangarh Mandi", "Rajaldesar", "Sujangarh", "Salasar"],
      "Sardarshahar": ["Sardarshahar Town", "Bhanipura", "Taranagar", "Sahawa"]
    },
    "Hanumangarh": {
      "Nohar": ["Nohar Mandi", "Bhadra", "Gogamedi", "Rawatsar", "Pilibanga"],
      "Tibbi": ["Tibbi Town", "Sangaria Mandi", "Talwara", "Dholipal"]
    },
    "Barmer": {
      "Balotra": ["Balotra City", "Jasol", "Siwana", "Pachpadra", "Samdari"],
      "Baytoo": ["Baytoo Rural", "Guda Malani", "Sindhari", "Sheo", "Chohtan"]
    },
    "Jalore": {
      "Bhinmal": ["Bhinmal Mandi", "Sanchore", "Raniwara", "Bagra", "Ahore"],
      "Sayla": ["Sayla Rural", "Jalore Sadar", "Jaswantpura", "Chitalwana"]
    },
    "Sirohi": {
      "Abu Road": ["Abu Road City", "Mount Abu Rural", "Sheoganj", "Reodar", "Pindwara"]
    },
    "Chittorgarh": {
      "Nimbahera": ["Nimbahera Mandi", "Chhoti Sadri", "Bari Sadri", "Rawatbhata", "Kapasan", "Begun"]
    },
    "Rajsamand": {
      "Nathdwara": ["Nathdwara Rural", "Kankroli", "Amet", "Deogarh", "Kumbhalgarh", "Railmagra"]
    },
    "Dungarpur": {
      "Sagwara": ["Sagwara Mandi", "Aspur", "Simalwara", "Dungarpur Rural", "Bichhiwara"]
    },
    "Banswara": {
      "Kushalgarh": ["Kushalgarh Rural", "Ghari", "Bagidora", "Talwara", "Anandpuri"]
    },
    "Pratapgarh": {
      "Arnod": ["Arnod Rural", "Dhariawad", "Peepalkhoont", "Pratapgarh Sadar"]
    },
    "Jhalawar": {
      "Jhalrapatan": ["Jhalrapatan Mandi", "Aklera", "Pirawa", "Khanpur", "Manohar Thana"]
    },
    "Baran": {
      "Chhabra": ["Chhabra Mandi", "Atru", "Kishanganj", "Shahbad", "Antah"]
    },
    "Bundi": {
      "Keshoraipatan": ["Keshoraipatan Mandi", "Hindoli", "Nainwa", "Indragarh", "Talera"]
    },
    "Sawai Madhopur": {
      "Gangapur City": ["Gangapur Mandi", "Bamanwas", "Bonli", "Chauth Ka Barwara", "Malarna Doongar"]
    },
    "Karauli": {
      "Hindaun City": ["Hindaun Mandi", "Todabhim", "Sapotra", "Mandrail", "Karanpur"]
    },
    "Dholpur": {
      "Bari": ["Bari Town", "Rajakhera", "Baseri", "Saipau", "Sarmathura"]
    }
  },
  "Punjab": {
    "Ludhiana": {
      "Ludhiana West": ["Baddowal", "Ayali Kalan", "Barundi", "Thakarwal"],
      "Jagraon": ["Sohian", "Kaunke Kalan", "Swaddi Khas", "Dakha"],
      "Khanna": ["Khanna Mandi", "Samrala", "Payal", "Machhiwara"]
    },
    "Patiala": {
      "Nabha": ["Alohran", "Rohti Chhanna", "Kakrala", "Bhadson"],
      "Samana": ["Ghagga", "Tarkhan Majra", "Kakepur", "Dyalgarh"],
      "Rajpura": ["Rajpura Town", "Ghanaur", "Patran", "Sanaur"]
    },
    "Amritsar": {
      "Ajnala": ["Ajnala Rural", "Chogawan", "Majitha", "Attari", "Jandiala Guru"]
    },
    "Bathinda": {
      "Talwandi Sabo": ["Talwandi Sabo Mandi", "Rampura Phul", "Maur", "Goniana", "Bhucho Mandi"]
    }
  },
  "Haryana": {
    "Karnal": {
      "Karnal Sadar": ["Kachhwa", "Taraori", "Kunjpura", "Nilokheri"],
      "Gharaunda": ["Kohand", "Bastara", "Chaura", "Barsat"],
      "Assandh": ["Assandh Mandi", "Jaisinghpura", "Rahra", "Salwan"]
    },
    "Kurukshetra": {
      "Thanesar": ["Umri", "Pipli", "Mirzapur", "Dhand"],
      "Pehowa": ["Gumthala", "Saraswati Nagar", "Ismailabad", "Bodhi"],
      "Shahbad": ["Shahbad Markanda", "Babain", "Ladwa", "Barara"]
    },
    "Sirsa": {
      "Dabwali": ["Mandi Dabwali", "Kalanwali", "Rania", "Ellenabad", "Ding"]
    }
  },
  "Madhya Pradesh": {
    "Indore": {
      "Sanwer": ["Sanwer Rural", "Kshipra", "Dharampuri", "Chandrawatiganj"],
      "Depalpur": ["Betma", "Gautampura", "Ghatabillod", "Biroda"],
      "Mhow": ["Mhow Cantonment", "Manpur", "Hasalpur", "Simrol"]
    },
    "Ujjain": {
      "Tarana": ["Kayatha", "Narania", "Khadotara", "Sumrakheda"],
      "Mahidpur": ["Khedakhajuria", "Gogapur", "Jharda", "Nalkheda"],
      "Nagda": ["Nagda Mandi", "Khachrod", "Unhel", "Barnagar"]
    },
    "Bhopal": {
      "Berasia": ["Berasia Town", "Nazeerabad", "Gunaga", "Runaha"]
    }
  },
  "Uttar Pradesh": {
    "Mathura": {
      "Chhata": ["Kosi Kalan", "Nandgaon", "Barsana", "Shergarh"],
      "Mant": ["Raya", "Bajna", "Naujheel", "Surir"],
      "Govardhan": ["Govardhan Rural", "Radhakund", "Aring", "Magorra"]
    },
    "Agra": {
      "Fatehabad": ["Dhimshree", "Rundhi", "Sarhendi", "Tehra"],
      "Etmadpur": ["Khandauli", "Barhan", "Garhi", "Semra"],
      "Kheragarh": ["Kheragarh Town", "Saiyan", "Jagner", "Kagarol"]
    },
    "Aligarh": {
      "Atrauli": ["Atrauli Mandi", "Harduaganj", "Chharra", "Gulaothi"]
    }
  }
};
